---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.zhengxh
--- DateTime: 2019/10/25 15:22
---


------------------------------------------------------------------------------------------
--- 处理玩家登录时同过Sql Server数据库查询玩家数据
------------------------------------------------------------------------------------------

--- 从SqlServer加载玩家User数据
--- @param UserID 玩家UserID
--- @param User 玩家User的table
function LoadUserInfoFromSQLServer(UserID, User)
    if User == nil then
        Logger("LoadUserInfoFromSQLServer User nil")
        return User
    end
    -- 1.加载 AccountsInfo
    local sSql = ""
    sSql = string.format("SELECT UserID,GameID,NickName,FaceID,Gender,Experience,LoveLiness,Lev,VipLev,"..
            "VipExp,AccountLev,PayTotal,DATEDIFF(S, '1970-01-01 08:00:00', OffLineTime) AS OffLineTime FROM AccountsInfo WHERE UserID = %d;", UserID)
    local ret = SqlServerDataBaseBYQuery(sSql)
    if #ret == 0 then
        -- 没有找到玩家数据
        Logger("LoadUserInfoFromSQLServer AccountsInfo 返回 nil")
        return User
    else
        for k,v in pairs(User) do
            if ret[1][k] ~= nil then
                User[k] = ret[1][k]       -- 将数据库保存数据赋值
            end
        end
    end

    -- 2.加载 GameScoreInfo
    sSql = string.format("SELECT Score,Diamond FROM GameScoreInfo WHERE UserID = %d;",UserID)
    ret = SqlServerDataBaseBYQuery(sSql)
    if #ret == 0 then
        -- 没有找到玩家数据
        Logger("LoadUserInfoFromSQLServer GameScoreInfo 返回 nil")
        return User
    else
        User.Score      = ret[1].Score
        User.Diamond    = ret[1].Diamond
    end

    -- 3.加载 UserSkillInfo
    sSql = string.format("SELECT ItemID,Used,Total,UsedTime FROM UserSkillInfo WHERE UserID = %d;",UserID)
    ret = SqlServerDataBaseBYQuery(sSql)
    if #ret == 0 then
        -- 没有找到玩家数据
        Logger("LoadUserInfoFromSQLServer UserSkillInfo 返回 nil")
    else
        User.SkillInfoArray = ret
    end

    -- 4.加载 UserSeaMonster
    sSql = string.format("SELECT MosterID AS MonsterID,MosterHp AS MonsterHP,ButtleNum AS MonsterBulletNum,"..
            "TotalCritNum,DATEDIFF(S, '1970-01-01 08:00:00', SummonDate) AS SummonTimes,"..
            "DATEDIFF(S, '1970-01-01 08:00:00', StartDate) AS StartDate, Puzzle FROM UserSeaMonster "..
            "WHERE UserID = %d;",UserID)
    ret = SqlServerDataBaseBYQuery(sSql)
    if #ret == 0 then
        -- 没有找到玩家数据
        --Logger("LoadUserInfoFromSQLServer UserSeaMonster 返回 nil")
        -- 写入新数据
        sSql = string.format("Insert Into UserSeaMonster(UserID,MosterID,MosterHp,ButtleNum,TotalCritNum,SummonDate) "..
                "values(%d,0,0,0,0,getdate());",UserID)
        SqlServerDataBaseBYExec(sSql)
        User.MonsterID       = 0
        User.MonsterHP       = 0
        User.MonsterBulletNum= 0
        User.TotalCritNum    = 0
        User.SummonTimes     = 0
        User.PuzzleIDArray   = StringSplitToNumberArray("",",",9)
        -- 给一个召唤石
        table.insert(User.SkillInfoArray, #User.SkillInfoArray+1, {ItemID=7001,Used=0,Total=1,UsedTime=0})
    else
        User.MonsterID       = ret[1].MonsterID
        User.MonsterHP       = ret[1].MonsterHP
        User.MonsterBulletNum= ret[1].MonsterBulletNum
        User.TotalCritNum    = ret[1].TotalCritNum
        User.SummonTimes     = ret[1].StartDate
        -- 上次召唤是否跨天
        if ret[1].StartDate == nil or GetTwoTimesDays(ret[1].StartDate, os.time()) > 0 then
            User.MonsterID       = 0
            User.MonsterHP       = 0
            User.MonsterBulletNum= 0
            User.TotalCritNum    = 0
            User.SummonTimes     = 0
        end
        -- 上次领取道具是否跨天
        if GetTwoTimesDays(ret[1].SummonTimes, os.time()) > 0 then
            sSql = string.format("UPDATE UserSeaMonster WITH(ROWLOCK,UPDLOCK) SET SummonDate=getdate() WHERE UserID= %d;",UserID)
            SqlServerDataBaseBYExec(sSql)
            -- 给一个召唤石
            table.insert(User.SkillInfoArray, #User.SkillInfoArray+1, {ItemID=7001,Used=0,Total=1,UsedTime=0})
        end
        User.PuzzleIDArray   = StringSplitToNumberArray(ret[1].Puzzle,",",9)
    end

    return User
end

------------------------------------------------------------------------------------------
--- 通过NickName或者GameID查找玩家UserID
--- @param sKey 查找的GameID或者GameID
--- @return dwUserID
function LoadUserIDFromSQLServer(sKey)
    local dwUserID
    local dwGameID = tonumber(sKey)
    if dwGameID == nil then
        dwGameID = -1
    end
    local sSql = string.format("SELECT UserID FROM AccountsInfo WHERE NickName = '%s' OR GameID = %d;", sKey, dwGameID)
    local ret = SqlServerDataBaseBYQuery(sSql)
    if ret == nil or #ret == 0 then
        return nil
    else
        dwUserID = ret[1].UserID -- 去返回值第一个作为玩家需要查询的信息
    end
    return dwUserID
end
------------------------------------------------------------------------------------------