---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.zhengxh
--- DateTime: 2019/10/30 10:08
---

------------------------------------------------------------------------------------------
--- 处理保存玩家游戏记录
------------------------------------------------------------------------------------------

--- 获取表名(Table+time)
--- @param tableName    表名前缀
local function GetTableName(tableName)
    return string.format("%s_%s",tableName, GetOsDayNowEx())
end

--- 保存游戏记录
--- @param userID                   用户userID
--- @param strItem                  投注信息
--- @param llChipTotal              下注统计
--- @param llWinScore               总赢金币
--- @param llWinLottery             总赢奖券
--- @param llWinDiamond             总赢钻石
--- @param strDst                   中奖信息
--- @param gmControlStatus          gm控制信息
--- @param fishID                   鱼ID
--- @param llPumpingStoreChange     抽水改变库存值
--- @param llWinCoinExtra           玩家妖精场礼包额外获得灵力
--- @param llCostTrueValutJackpot   真金库改变值
function SaveGameRecord(userID,strItem,llChipTotal,llWinScore,llWinLottery,llWinDiamond,strDst,gmControlStatus,fishID,
                        llPumpingStoreChange,llWinCoinExtra,llCostTrueVaultJackpot)
    -- 必传参数验证
    if userID == nil or strItem == nil or llChipTotal == nil or llWinScore == nil or llWinLottery == nil
            or llWinDiamond == nil or strDst == nil then
        Logger(string.format("SaveGameRecord 参数有误:%d,%s,%lld,%lld,%lld,%lld,%s",userID,strItem,
                llChipTotal,llWinScore,llWinLottery,llWinDiamond,strDst))
        return
    end
    -- 默认参数处理
    gmControlStatus         = gmControlStatus        or 0
    fishID                  = fishID                 or 0
    llPumpingStoreChange    = llPumpingStoreChange   or 0
    llWinCoinExtra          = llWinCoinExtra         or 0
    llCostTrueVaultJackpot  = llCostTrueVaultJackpot or 0

    local tableName = GetTableName("HunGameChipRecord")
    local sSql = string.format("Insert Into %s(UserID,ClientKind,KindID,ServerID,GameNum,ChipTotal,"..
            "WinScore,ChipItem,HitDst,RecordTime,TableArea,UserScore,UserInsure,ControlID,WinLottery,UserLottery,"..
            "WinDiamond,UserDiamond,GmControlStatus,FishKindID,PumpStoreChange,CurrentStore,WinCoinExtra) Values(%d,"..
            "%d,%d,%d,%d,%d,%d,'%s','%s',GetDate(),%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d);",
            tableName,userID,0,0,0,0,llChipTotal,llWinScore,strItem,strDst,0,0,llCostTrueVaultJackpot,0,llWinLottery,
            0,llWinDiamond,0,gmControlStatus,fishID,llPumpingStoreChange,0,llWinCoinExtra)
    SqlServerDataBaseLogExec(sSql)
end