---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/2 16:48
---

local FishServerExcel = require("mgby_fish_sever")

Fish = {}

function Fish:New(uid)
    c = {
        FishUID = uid, --UID
        FishKindID = 0, -- 鱼的表中的类型， 是小丑鱼，娃娃鱼，还是锤头鲨
        FishType = 0, -- 鱼大的分类类型， 是大鱼，小鱼，中鱼，还是boss

        DeadTime = 0, -- 过期时间
        PathID = 0, -- 路径
        --pathIndex int		-- 路径索引
        OffsetX = 0,
        OffsetY = 0,
        Speed = 0,
        --
        Mulriple = 0, -- 倍率
        CapturePro = 0, -- 捕获率
        --
        CreateTime = 0, -- 创建时间
        TotalAliveTime = 0, -- 存活时间，秒
        --MovePerPointTime time.Time	-- 移动一个坐标点需要的时间
    }
    setmetatable(c, self)
    self.__index = self
    return c
end

function Fish:Run(table)
    if GetOsTimeMillisecond() > self.DeadTime then
        print("鱼生存时间到了")
        table:DelFish(self.FishUID)
    end

end

-- 创建一条鱼
function Fish:CreateFish(kindId,x,y,PathID)
    local now = GetOsTimeMillisecond()
    local speed = FishServerExcel[kindId].speed
    local Mulriple = FishServerExcel[kindId].mulriple
    local CapturePro = FishServerExcel[kindId].capture_probability
    local totalAliveTime = 120

    self.FishKindID = kindId
    self.FishType = FishServerExcel[kindId].type
    self.CreateTime = now
    self.TotalAliveTime = totalAliveTime
    self.DeadTime = now + self.TotalAliveTime * 1000
    self.Speed = speed
    self.PathID = PathID
    self.Mulriple = Mulriple
    self.CapturePro = CapturePro

    return self
end

-- 获取鱼的分数
function Fish:GetFishScore()
    return FishServerExcel[self.FishKindID].gold_multiples
end