---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1 14:59
---

ByTable = {}


function ByTable:New(tableId,gameTypeId)
    c = {
        GameID = gameTypeId,
        TableID = tableId,
        TableMax = BY_TABLE_MAX_PLAYER, --桌子容纳玩家数量
        RoomScore = 0,  --房间分数

        UserSeatArray = {},  -- 座椅对应玩家uid的哈希表 ， key ： seat ，value： 玩家uid


        GenerateFishUid = 0, -- 生成鱼的uid
        GenerateBulletUid = 0, -- 生成子弹的uid

        FishArray = {},   -- 鱼的哈希表
        BulletArray = {},   -- 子弹的哈希表


        DistributeArray = {},   -- 鱼的生成信息数据
        BossDistributeArray = {},   -- Boss鱼的生成信息数组
    }
    setmetatable(c,self)
    self.__index = self
    return c
end

function ByTable:InitTable()
--    luaCallGoCreateGoroutine("RunTable")
    FindGoRoutineAndRegisterTableRun(self.RunTable())    -- 注册开始一个新的协程
end
function ByTable:RunTable()
print("RunTable")
end