---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1 13:32
---
----------------------------------------------------------------
-----------------------------game管理桌子和玩家-----------------
----------------------------------------------------------------
package.path = "Script/Games/BY/?.lua;"..package.path
require("byTable")

Game = {}

function Game:New(name,gameTypeId, switch)
    c = {
        Name = name,
        Id = gameTypeId,
        Switch = switch,    -- 游戏是否开启

        AllTableList = {},  -- 所有桌子列表
        TableUUID = 0,

        AllUserList = {},   -- 所有玩家列表
    }
    setmetatable(c,self)
    self.__index = self
    return c
end


----------------------------------------------------------------
-----------------------------管理桌子---------------------------
----------------------------------------------------------------

-- 创建桌子，并启动它
function Game:CreateTable(gameType,gameScore)
    local table_t
    if gameType == GameTypeBY then
        table_t =  ByTable:New(self.TableUUID, gameType)
        --printTable(table_t)
    elseif gameType == GameTypeBY2 then

    elseif gameType == GameTypeBY3 then

    end
    if table_t == nil then
        Logger("CreateTable error , gameType"..gameType)
        return
    end
    table_t.RoomScore = gameScore
    Logger("创建了一个新的桌子,type:"..gameType)

    --增加该桌子到总列表中
    self.AllTableList[self.TableUUID] = table_t
    self.TableUUID = self.TableUUID + 1     -- table uuid 自增

    -- 桌子开始自行启动计算
    table_t:RunTable()



end

-- 根据桌子uid 返回桌子的句柄
function Game:GetTableByUID(tableId)
    return self.AllTableList[tableId]
end

----------------------------------------------------------------
-----------------------------管理玩家---------------------------
----------------------------------------------------------------
-- 根据user uid 返回user的句柄
function Game:GetUserByUID(uid)
    return self.AllUserList[uid]
end

-- 有玩家登陆游戏，想进入对应分数的房间
function PlayerLoginGame()

end

--玩家登出
function PlayerLogOutGame()

end