---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/9 14:12
---

--print("start lua")


package.path = "Script/?.lua;"..package.path
require("server")
