---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/12 15:00
---


local function reloadFile(module_name)
    package.loaded[module_name] = nil
    require(module_name)
end


-- 热更新全部的逻辑代码，需要自己控制， 切记玩家数据部分不要加进去，不然会重置玩家数据，如果你是保存型代码，容易导致玩家清档
function ReloadAll()

--    Logger("------------------start reload all---------------------------")

--    reloadFile("Script/HotReload/hotReload")
--    reloadFile("Script/Const")
--    reloadFile("Script/GameCommonLogic/commonLogic")
--    reloadFile("Script/Loger/loger")
--    reloadFile("Script/NetWork/network")
--    reloadFile("Script/Protocol/build/user_pb")
--    reloadFile("Script/CSV/mgby_fish_sever")


end


