---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/11 15:36
---

------------------------------------------------------------------------------------------
--- 这里有2种方式调用mysql
--- 第一种是通过go调用，适用于对性能有要求，并且没有返回的情况
--- 第二种是通过lua调用， 性能会差很多，会有延迟， 但是可以获取到select的返回值，并且是table类型的
------------------------------------------------------------------------------------------


SQLStaticSwitch = true     -- 统计的数据保存到数据库中开关


----------------------------保存服务器状态信息，是按照时间保存的，可以看历史记录-----------------------------
function SqlSaveServerState(state)
    if SQLStaticSwitch then
        local time= ZTime.GetOsDateNow()
        local sql = string.format("insert into server_state (server_ip,time,table_num,player_num,rece_num,send_num, write_chan, head_err , heap_inuse, network_delay ) values ('%s','%s', %d,%d,%d,%d,%d,%d,%d,%d)",
                GlobalVar.ServerIP_Port,time,state.TableNum,state.PlayerNum,state.ReceiveNum,state.SendNum,state.WriteChannelNum,state.HeadErrorNum , state.HeapInUse, state.NetWorkDelay)
        MySql.Exec(sql)
    end
end


-- 保存服务器的房间状态
local function ZMySqlSaveGameState(ServerIP_Port,gameType,roomId ,FishNum,BulletNum,SeatArray)
    -- 想想如何处理

    --luaCallGoSqlSaveGameState(ServerIP_Port,gameType,roomId ,FishNum,BulletNum,SeatArray)
end


----------------------------保存房间状态信息，当前的运行信息，房间销毁就删掉-----------------------------
function SqlSaveGameState(gameType,roomId, state)
    if SQLStaticSwitch then

        ZMySqlSaveGameState(GlobalVar.ServerIP_Port,gameType,roomId ,state.FishNum,state.BulletNum,state.SeatArray)   -- 采用go来做这个事情了， lua太费性能

        --RedisSaveString(RedisDirGameState..ServerIP_Port..":GameID_"..gameType..":roomId"..roomId, roomId, ZJson.encode(state))

        --local select = string.format("select * from game_state where server_ip = '%s' and game_id = %d and table_id = %d",ServerIP_Port,gameType,roomId )
        --local insert = string.format("insert into game_state (server_ip,game_id,table_id,fish_num,bullet_num,seat_array) values ('%s',%s, %d,%d,%d,%d)",ServerIP_Port,gameType,roomId ,state.FishNum,state.BulletNum,state.SeatArray)
        --local update = string.format("update  game_state   set  fish_num =%d ,bullet_num =%d,seat_array=%d where server_ip = '%s' and game_id = %d and table_id = %d",state.FishNum,state.BulletNum,state.SeatArray,ServerIP_Port,gameType,roomId )
        ----print(select)
        ----print(insert)
        ----print(update)
        --
        --local re = MysqlQuery(select)
        --if #re == 0 then
        --    --print("insert")
        --    MysqlExec(insert)
        --else
        --    --print("update")
        --    MysqlExec(update)
        --end


        --insert into vclb_mm_inventory (`ID_`, `STOCK_ID_`, `ITEM_ID_`, `AMOUNT_`)
        --values ('1', '1', '1', 44)
        --ON DUPLICATE KEY UPDATE `AMOUNT_` = `AMOUNT_` + 44;
    end

end
----------------------------删掉房间状态信息-----------------------------
function SqlDelGameState(gameType,roomId)         -- 清理掉房间的运行状态
    if SQLStaticSwitch then
        local sql = string.format("delete from game_state where server_ip = '%s' and game_id = %d and table_id = %d ",GlobalVar.ServerIP_Port,gameType,roomId)
        --print(sql)
        MySql.Exec(sql)
    end
end
