---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.zhengxh
--- DateTime: 2019/11/1 18:59
---

--------------------------------------------------------------------------------------
--- 主要处理玩家拼图
--------------------------------------------------------------------------------------

--- 玩家拼图消息处理
--- @param player 玩家
--- @param data   消息数据
function XhsTable:HandleOnUserPlayPuzzle(player,data)
    -- 玩家验证
    Logger("HandleOnUserPlayPuzzle plyaer 为nil")
    if player == nil then
        Logger("HandleOnUserPlayPuzzle plyaer 为nil")
        return
    end

    -- 解析消息
    local receiveMsg = CMD_XHS_Game_pb.CMD_C_PLAY_PUZZLE_REQ()
    receiveMsg:ParseFromString(data)

    -- 获取玩家user对象
    local user = player.User
    if user == nil then
        Logger("HandleOnUserPlayPuzzle user 为nil")
        return
    end
    -- 拼图碎片验证
    local puzzleId = receiveMsg.puzzle_id
    local excelPuzzleItemType = GetExcelItemValue(puzzleId, "item_type")
    if excelPuzzleItemType ~= Enum_ItemType.eItemType_JsGsaw_Chip then
        Logger("HandleOnUserPlayPuzzle excelPuzzleItem.item_type 不是拼图碎片类型")
        return
    end
    local result = 0
    -- 获取玩家该道具碎片
    local userItem = nil
    for i, v in pairs(user.SkillInfoArray) do
        if v.ItemID == puzzleId then
            userItem = v
            break
        end
    end
    -- 道具验证
    if userItem == nil or userItem.Used >= userItem.Total then
        result = 1
    end
    -- 位置验证
    if result == 0 then
        for i, v in pairs(user.PuzzleIDArray) do
            if v == puzzleId then
                result = 2 -- 该位置已经存在碎片
                break
            end
        end
    end
    -- 拼图面板是否已经满了
    if result == 0 then
        local bFull = true
        for i, v in pairs(user.PuzzleIDArray) do
            if v == 0 then
                bFull = false
                break
            end
        end
        -- 没有位置了
        if bFull then
            result = 3
        end
    end

    -- 拼图失败
    if result ~= 0 then
        local sendResult = CMD_XHS_Game_pb.CMD_S_PLAY_PUZZLE_RESULT()
        sendResult.result = result
        LuaNetWorkSendToUser(player.User.UserID, MDM_GF_GAME, SUB_S_PLAY_PUZZLE_RESULT, sendResult, nil, nil )
        return
    end

    -- 添加拼图碎片到拼图板
    for i, v in pairs(user.PuzzleIDArray) do
        if v == 0 then
            user.PuzzleIDArray[i] = puzzleId
            break
        end
    end
    -- 扣除该道具
    player:DecItem(puzzleId, 1)
    -- 保存玩家拼图信息
    self:SaveUserPuzzleInfo(user)
    -- 拼图成功返回消息
    local sendResult = CMD_XHS_Game_pb.CMD_S_PLAY_PUZZLE_RESULT()
    sendResult.result = result
    sendResult.puzzle_id = puzzleId
    LuaNetWorkSendToUser(user.UserID, MDM_GF_GAME, SUB_S_PLAY_PUZZLE_RESULT, sendResult, nil, nil)

    -- 如果玩家成拼图，做游戏记录
    local bFull = true
    for i, v in pairs(user.PuzzleIDArray) do
        if v == 0 then
            bFull = false
            break
        end
    end
    if bFull then
        -- 记录游戏
        SaveGameRecord(user.UserID,"[DHS]完成拼图",0,0,0,0,"")
    end
end

--- 玩家领取拼图奖励处理
--- @param player 玩家
--- @param data   消息数据
function XhsTable:HandleOnUserGetPuzzleAward(player,data)
    -- 玩家验证
    if player == nil then
        Logger("HandleOnUserGetPuzzleAward plyaer 为nil")
        return
    end

    -- 获取玩家user对象
    local user = player.User
    if user == nil then
        Logger("HandleOnUserGetPuzzleAward user 为nil")
        return
    end

    -- 解析消息
    local receiveMsg = CMD_XHS_Game_pb.CMD_C_PUZZLE_REWARD_REQ()
    receiveMsg:ParseFromString(data)

    local result = 0
    -- 验证拼图版拼图碎片数量
    local bFull = true
    for i, v in pairs(user.PuzzleIDArray) do
        if v == 0 then
            bFull = false
            break
        end
    end
    if bFull == false then result = 1 end

    -- 未完成
    if result ~= 0 then
        local sendResult = CMD_XHS_Game_pb.CMD_S_PUZZLE_REWARD_RESULT()
        sendResult.result = result
        LuaNetWorkSendToUser(player.User.UserID, MDM_GF_GAME, SUB_S_PUZZLE_REWARD_RESULT, sendResult, nil, nil)
        return
    end
    -- 获取海兽ID
    local excelItemMonsterID = GetExcelItemValue(user.PuzzleIDArray[1],"monster_id")
    -- 获取当前玩家海兽信息
    local excelXhsPuzzleGoldWeights = GetExcelXhsValue(excelItemMonsterID, "puzzle_gold_weights")
    local excelXhsPuzzleGoldNum = GetExcelXhsValue(excelItemMonsterID, "puzzle_gold_num")

    -- 清理玩家拥有的拼图碎片
    for i, v in pairs(user.PuzzleIDArray) do
        user.PuzzleIDArray[i] = 0
    end
    -- 保存玩家拼图信息
    self:SaveUserPuzzleInfo(user)
    -- 发奖励
    local awardGold = 0
    local weightIndex = TableWeightSelect(excelXhsPuzzleGoldWeights)
    awardGold = excelXhsPuzzleGoldNum[weightIndex]
    -- 游戏记录
    user.Score = user.Score + awardGold
    -- 返回客户端结果
    local sendResult = CMD_XHS_Game_pb.CMD_S_PUZZLE_REWARD_RESULT()
    sendResult.result = result
    sendResult.money = awardGold
    local randItem = GetRandom(1,10000)
    local awardItemID,awardItemNum = 0, 0
    local strDst = ""
    local excelXhsPuzzleItemProbability = GetExcelXhsValue(excelItemMonsterID,"puzzle_item_probability")
    local excelXhsPuzzleItemID = GetExcelXhsValue(excelItemMonsterID,"puzzle_item_id")
    local excelXhsPuzzleItemNum = GetExcelXhsValue(excelItemMonsterID,"puzzle_item_num")
    for i, v in pairs(excelXhsPuzzleItemProbability) do
        -- 最多奖励5个
        if i > 5 then break end
        -- 每一个判定概率
        if v > randItem then
            awardItemID, awardItemNum = excelXhsPuzzleItemID[i], excelXhsPuzzleItemNum[i]
            if awardItemID > 0 and awardItemNum > 0 then
                -- 增加道具
                player:AddItem(awardItemID, awardItemNum)
                -- 拼装消息
                local itemAward = sendResult.user_items:add()
                itemAward.item_id   = awardItemID
                itemAward.item_num  = awardItemNum
                strDst = string.format("%s%d:%d;",strDst,awardItemID,awardItemNum)
            end
        end
    end
    -- 游戏记录
    SaveGameRecord(user.UserID,"领取碎片奖励",0,awardGold,0,0,strDst)
    LuaNetWorkSendToUser(user.UserID, MDM_GF_GAME, SUB_S_PUZZLE_REWARD_RESULT, sendResult, nil, nil)
end