---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/21 16:20
---


------------------------统计信息用-----------------------
ServerIP_Port = ""      -- 当前服务器的地址和端口号
ServerStateSendNum = 0      -- 平均网络发送包数量
ServerStateReceiveNum = 0   -- 平均网络接收包数量







------------------------游戏和玩家列表-----------------------
AllGamesList = {}   -- gameType , game
AllPlayerList = {}   -- 所有玩家列表   key  userId , value player

ALLUserUUID = 0   -- 玩家uid的自增

