---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1 14:34
---

-------------------------------------说明----------------------------------------
---本文件是服务器启动的时候加载使用
-----------------------------------------------------------------------------


-------------------------------------CSV----------------------------------------
package.path = "Script/CSV/?.lua;"..package.path
--data_csv1 = require("mgby_fish_sever")
--print(data_csv1[134].type)
--print(data_csv1[134].min_force_killed_bullet)
--Logger("csv ok")

-------------------------------------protocol buffer----------------------------------------
package.path = "Script/Protocol/build/?.lua;"..package.path
package.path = "Script/Protocol/protobuf/?.lua;"..package.path
--require("protocol_test")
--Logger("protocol buffer ok")

-------------------------------------Const----------------------------------------

package.path = "Script/NetWork/?.lua;"..package.path
package.path = "Script/GameCommonLogic/?.lua;"..package.path
package.path = "Script/HotReload/?.lua;"..package.path
package.path = "Script/Const/?.lua;"..package.path
package.path = "Script/Utils/?.lua;"..package.path
package.path = "Script/GlobalVar/?.lua;"..package.path
package.path = "Script/GameManager/?.lua;"..package.path

require("Const")
require("Excel")
require("Proto")
require("protocol_cs")
require("protocol_gs")
require("protocol_ls")


-------------------------------------Const----------------------------------------
require("commonLogic")
require("hotReload")
require("Time")
require("Random")
require("dumpTable")
require("zTable")
require("zRedis")
require("zMySql")

-------------------------------------Redis----------------------------------------
package.path = "Script/DataBase/?.lua;"..package.path
require("redisConst")
require("redisGame")
require("redisPlayer")


--Logger("system ok")
-------------------------------------NetWork----------------------------------------

--require("multiThreadChannel")
require("gameFire")
require("gameEnter")
require("LoginServer")
require("Statistic")
require("network")

-------------------------------------GameManager----------------------------------------

require("globalVar")
require("player")
require("user")

package.path = "Script/Games/BY/?.lua;"..package.path
require("byBullet")
require("byFish")
require("byFishDistribute")
require("byTable")

require("games")
require("gameManager")


--print(FishServerExcel["101"].type)
