---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/2 16:18
---
--------------------------------------------------------------------------------------
--- User 的数据是玩家的游戏中永久数据，需要保存的数据
------ 这里直接定义成员变量， 但是不写成员函数， 这样不用reload
--- 一定确保字段名与数据库表中字段名相同
--------------------------------------------------------------------------------------

User = Class:extend()
function User:New(userId,openId,machineId)

    --- 玩家基础信息
    self.userId = userId                --  # 用户id
    self.openId = openId
    self.machineId = machineId
    self.gameId = 0                --  # 游戏id
    self.nickName = "玩家"..userId               --  # 昵称
    self.level = 0                --  # 等级
    self.exp = 0                --  # 经验
    self.faceId = 0                --  # 头像id
    self.gender = 0                --  # 性别
    self.payTotal = 0                --  # 充值总金额
    self.offLineTime = 0                --  # 离线时间


end

function User:Reload(c)
    -- 如果热更新有改动成员变量的定义的话， 下面需要进行成员变量的处理
    -- 比如 1 增加了字段， 那么你需要将老数据进行， 新字段的初始化
    -- 比如 2 删除了字段， 那么你需要将老数据进行， 老字段=nil
    -- 比如 3 修改了字段， 那么你需要将老数据进行， 老字段=nil， 新字段初始化或者进行赋值处理
end
