---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.
--- DateTime: 2019/5/21 13:44
---

--{
--    "id": 2,
--    "uuid": 1557903223760,
--    "mail": "6",
--    "userId": "6",
--    "serverId": "6",
--    "start_time": [
--    "2019-05-23 00:00:00",
--    "2019-06-25 00:00:00"   ],
--    "score": "6",
--    "item": "6",
--    "item_num": "6"
--}

-- 请求删除邮件，这里是真的删除邮件， 删除的是玩家的邮件列表数据
local function MailDelete(player,uuid)
    if player.User.MailList[uuid] ~= nil then
        player.User.MailList[uuid] = nil
        RedisSavePlayerAll(player.User)
    end
end



-- 检查系统邮件
function SystemCheckMail(player)

    --print(MySerpent.block(player))
    --print("系统邮件 player".. player.User.UserId)

    local list = RedisGetSystemMail()        -- 获得跑马灯列表， 这里获得的是一个json
    --print("list          "..list..type(list))
    if list == "null" then
        --print("redis mail 里面没有东西")
        return      -- redis里面没有数据
    end

    -- 首先要遍历所有的系统邮件，看看是否存在于玩家列表， 如果存在，判断一下状态， 如果不存在，那么增加到玩家的邮件列表里面

    local mail_list = ZJson.decode(list)     -- 解开json，里面是一个列表
    for _, mail_json in pairs(mail_list) do
        --print(mail_json)
        local mail_data = ZJson.decode(mail_json)        -- 每一个元素是一个json字符串， 这里是redis保存的原始格式

        local start_time = GetTimeFromString(mail_data.start_time[1])
        local end_time = GetTimeFromString(mail_data.start_time[2])
        local userId = tonumber(mail_data.userId)
        --local mail_text = mail_data.mail
        --local serverId = mail_data.serverId
        local uuid = tostring(mail_data.uuid)
        --local score = mail_data.score
        --local item = mail_data.item
        --local item_num = mail_data.item_num

        -- 判断系统邮件里面是否有需要收到玩家邮件列表中的
        local now = os.time()
        --print("userId       "..userId)
        if userId == 0 or player.User.UserId == userId then      -- 发给全体，或者是发给这个玩家
            if now > start_time and now < end_time then     -- 如果系统邮件时间满足了，可以收到用户手里了
                if player.User.MailList[uuid] == nil then       -- 并且用户还没有收取该邮件， 那么收取，并设置类型为普通
                    -- 不存在，那么增加进去
                    mail_data.mail_type = MailTypeNormal  -- 设置邮件状态为普通，就是未收取
                    player.User.MailList[uuid] = mail_data
                    print("增加系统邮件到玩家的邮件列表中")
                end
            end
        end
    end



    local sendCmd = CMD_GameServer_pb.CMD_S_Mail()
    sendCmd.max_count = 0

    -- 再遍历玩家的邮件列表，取出对应的邮件， 如果邮件超期，那么删除该邮件
    for uuid,mailTable in pairs(player.User.MailList) do
        if mailTable.mail_type ~= MailTypeDeleted then
            -- 如果邮件没有被删除，那么同步给客户端
            sendCmd.max_count = sendCmd.max_count + 1
            local message = sendCmd.message_list:add()
            message.index = tonumber(uuid)
            message.type = 1
            message.time = 1
            message.msg = mailTable.mail
            message.status = mailTable.mail_type
            message.gift_count = 1
            message.gift_type1 = tonumber(mailTable.item)
            message.gift_type2 = 1
            message.gift_type3 = 1
            message.gift_type4 = 1
            message.amount1 = tonumber(mailTable.item_num)
            message.amount2 = 1
            message.amount3 = 1
            message.amount4 = 1
            message.title = ""
            message.gift_score = tonumber(mailTable.score)

        end

        -- 检查一下邮件是否过期
        local end_time = GetTimeFromString(mailTable.start_time[2])
        local now = os.time()
        if  now > end_time  then        -- 如果当前时间已经超过了该邮件的截止收取日期
            if mailTable.mail_type == MailTypeDeleted then                      -- 如果邮件超过了收取的最后日期，并且已经删除了， 那么删掉记录
                MailDelete(player,uuid)        -- 删掉该邮件
            end
            if mailTable.mail_type == MailTypeNormal and GetTwoTimesDays( end_time ,now) >= 30 then   -- 如果没有领取奖励，超过了系统邮件的截止领取日期， 并且超过了30天
                MailDelete(player,uuid)
            end
            if mailTable.mail_type == MailTypeReceived and GetTwoTimesDays( end_time ,now) >= 3 then   -- 如果已经领取了奖励，超过了系统邮件的截止领取日期， 并且超过了3天
                MailDelete(player,uuid)
            end
        end
    end

    return sendCmd

end


--{
--    "id": 2,
--    "uuid": 1557903223760,
--    "mail": "6",
--    "userId": "6",
--    "serverId": "6",
--    "start_time": [
--    "2019-05-23 00:00:00",
--    "2019-06-25 00:00:00"   ],
--    "score": "6",
--    "item": "6",
--    "item_num": "6"
--}

-- 系统给一个玩家发送一封邮件
function MailSystemSendToPlayer(uid, txt, score)
    local mail_data = {}
    mail_data.mail_type = MailTypeNormal  -- 设置邮件状态为普通，就是未收取
    mail_data.uuid = tostring(GetOsTimeMillisecond())
    mail_data.mail = txt
    mail_data.userId = uid
    mail_data.score = score
    mail_data.item = 0
    mail_data.item_num = 0

    mail_data.start_time = {}
    mail_data.start_time[1] = GetOsDateNow()
    mail_data.start_time[2] = GetOsDateNow(os.time() + 60 * 60 * 24 * 2)

    local user
    local player = GetPlayerByUID(uid)
    if player == nil then   -- 不在线，保存到数据库
        user = RedisGetUserData(uid)      -- 读取玩家数据
    else        -- 在线， 保存到内存中
        user = player.User
    end
    user.MailList[mail_data.uuid] = mail_data
    RedisSavePlayerAll(user)                -- 保存玩家数据

end

