---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.
--- DateTime: 2019/6/11 14:37
---


--  充值的时候调用
function VipAdd(player, rmb)
    player.User.PayTotal = player.User.PayTotal + rmb       -- 充值金额增加

    -- 判断vip等级是否需要增加
    if player.User.VipLevel == 7 then
        return
    end

    local next_vip_rmb = GetExcelValue(TBVIPExcel,player.User.VipLevel + 1, "recharge_money" )
    if player.User.PayTotal >= next_vip_rmb then
        player.User.VipLevel = player.User.VipLevel + 1     -- 超过下一级金额，就升级vip

        -- 以后增加通知玩家，vip等级提升

        local sendCmd = CMD_GameServer_pb.CMD_S_Vip_Gold_Dole()
        sendCmd.vip_level = player.User.VipLevel
        sendCmd.rmb = player.User.PayTotal
        sendCmd.score = 0
        sendCmd.player_score = ScoreGet(player)
        LuaNetWorkSendToUser(player.User.UserId, MDM_GF_GAME_TB, SUB_S_VIP_INFO, sendCmd, nil , nil)
    end
end

-- vip 发放救济金
function VipGiveDole(player)
    -- vip登录发放救济金
    local dole_gold = GetExcelValue(TBVIPExcel, player.User.VipLevel, "daily_comp")

    -- 如果vip发放救济金 >0
    if dole_gold > 0 then
        local today_last  -- 今天和上次签到的时间差
        if player.User.VipDoleGetTime == "" then        -- 如果没有上次领取时间
            today_last = 2      -- 如果没有记录， 那么就认为可以领取
        else
            today_last = GetTwoTimesDays(GetTimeFromString(player.User.VipDoleGetTime) , os.time())     -- 有签到记录，那么就用计算的值
        end

        if today_last > 0 then        -- 如果今天没有领取过
            if ScoreGet(player) < dole_gold then    -- 如果金币数量不足
                    local sendCmd = CMD_GameServer_pb.CMD_S_Vip_Gold_Dole()
                    sendCmd.vip_level = player.User.VipLevel
                    sendCmd.rmb = player.User.PayTotal
                    sendCmd.score = dole_gold
                    sendCmd.player_score = dole_gold
                    LuaNetWorkSendToUser(player.User.UserId, MDM_GF_GAME_TB, SUB_S_VIP_INFO, sendCmd, nil , nil)

                    player.User.VipDoleGetTime = GetOsDateNow()     -- 记录领取时间
                    local add_score = dole_gold - ScoreGet(player)
                    player.User.Score = dole_gold

                    RedisSavePlayerAll(player.User)     -- 保存玩家数据

                    SqlSaveUserGetGoldByVipLog(player, add_score )                    -- 记录玩家vip领奖日志
                    SqlSaveSystemLogVipDole(0  , "Vip level "..player.User.VipLevel , add_score , player.User.UserId)              -- 系统记录日志
            end
        end
    end
end