---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.
--- DateTime: 2019/11/19 9:26

--- 好友申请列表信息


--- 加载后台申请好友列表
function ChatServerLogic:OnLoadApplyFriendController()
    local sSql = "select UserID, VipMin, VipMax, GunLvMin, GunLvMax, UserLvMin, UserLvMax, OnlineMin, OnlineMax from ApplyFriendController where IsActive = 1"
    local resT = SqlServerDataBaseFriendQuery(sSql)
    return resT
end

--- 更新请求控制
---@param userid 玩家的UID
function ChatServerLogic:OnUpdateApplyFriendController(userid)
    local sSql = string.format("update ApplyFriendController with(updlock) set IsActive = 0 where userid = %d;", userid)
    SqlServerDataBaseFriendExec(sSql)
end