---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhushiwei.
--- DateTime: 2020/12/8 14:13
---
CMD_MAIN= {
    -- 注册命令(MainCmd)
    MDM_SERVER = 1  ,    -- 服务器命令
    MDM_GAME_CCC = 2    ,    -- ccc游戏命令

}



