---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/6 10:53
---

------------------------------------------------------------------------------------------
--- csv操作相关:
--- 为什么通过这种方式调用属性，为了避免配置相关出错，相关属性不存在影响程序代码正常运营
--- 统一函数命名规则(GetExcel开头)
------------------------------------------------------------------------------------------

--- excel 获取数据内部接口
---  excel    csv对象
---  index    主键
---  key      属性名
---  name     表名
---  该属性名的值
local function GetValue(excel, index, key)
    if excel[tostring(index)] == nil then
        ZLog.Logger(string.format("Excel 获取表: 主键:%s 出错!", index))
        return nil
    end
    if excel[tostring(index)][tostring(key)] == nil then
        ZLog.Logger(string.format("Excel 获取表: 主键:%s 列名:%s 出错!", index, key))
        return nil
    end

    return excel[tostring(index)][tostring(key)]
end

--- 获取配置表中的所有key
local function GetAllKeys(excel)
    local keys = {}
    for k in pairs(excel) do
        keys[#keys + 1] = k
    end
    if #keys == 0 then
        ZLog.Logger(string.format("Excel 获取表: 所有主键出错"))
        return nil
    end
    return keys
end


--------------------------------------------mgby_item.lua----------------------------------------------
--local ItemExcel = resourceType.resourceType
----- 获取mgby_item.csv数据对外接口
---- @param index    主键
---- @param key      属性名
------ @return 表mgby_item主键index所对应对象数据中key属性的值
--function GetExcelItemValue(index, key)
--    return GetValue(ItemExcel, index, key)
--end
----- 获取 mgby_item.csv中所有的key
------ @return 表mgby_item所有key组成的table
--function GetExcelItemAllKeys()
--    return GetAllKeys(ItemExcel)
--end