---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.zhengxh
--- DateTime: 2019/10/30 10:05
---

------------------------------------------------------------------------------------------
--- 处理玩家数据的保存和更新(对于特定游戏的数据保存我们在特定游戏中处理eg:xhsDB.Lua中出小海兽游戏相关的数据)
---1.对于玩家的基础数据采用每个一段时间保存一次&离线保存两种方式(eg:AccountsInfo、GameScoreInfo)
---2.对于非基础数据的我们采用实时保存，游戏产销保存(eg:UserSkillInfo)
------------------------------------------------------------------------------------------

--- 保存玩家基础数据
--- @param user 玩家User信息
function SaveUserBaseData(user)
    if user == nil then
        Logger("SaveUserBaseData user nil")
        return
    end
    local sSql = ""
    --- 1.AccountsInfo
    sSql = string.format("Update AccountsInfo Set NickName='%s',FaceID=%d,Gender=%d,Experience=%d,"..
            "LoveLiness=%d,Lev=%d,VipLev=%d,VipExp=%d,AccountLev=%d,PayTotal=%d Where UserID = %d;",user.NickName,
            user.FaceID, user.Gender, user.Experience, user.LoveLiness, user.Lev, user.VipLev, user.VipExp,
            user.AccountLev, user.PayTotal, user.UserID)
    SqlServerDataBaseBYExec(sSql)
    --- 2.GameScoreInfo
    sSql = string.format("Update GameScoreInfo Set Score=%d,Diamond=%d Where UserID = %d;",
            user.Score,user.Diamond, user.UserID)
    SqlServerDataBaseBYExec(sSql)
end

--- 保存玩家道具扣除
--- @param userID       玩家UserID
--- @param itemID       道具ID
--- @param usedChange   使用数量
function SaveUserItemDec(userID,itemID,usedChange)
    local sSql = string.format("update UserSkillInfo set Used += %d,UsedTime = %d,LastWriteDate=GetDate() "..
                "where UserID = %d and ItemID = %d;",usedChange,os.time(),userID,itemID)
    SqlServerDataBaseBYExec(sSql)
end

--- 保存玩家道具增加
--- @param userID       玩家UserID
--- @param itemID       道具ID
--- @param totalChange  使用数量
--- @param bNew         是否新增道具
function SaveUserItemAdd(userID,itemID,totalChange,bNew)
    local sSql = ""
    if bNew then
        sSql = string.format("insert into UserSkillInfo(UserID,SkillID,Total,Used,UsedTime,ItemID,"..
                "TodayCatch,LastWriteDate,Expiration) VALUES(%d,0,%d,%d,%d,%d,0,GetDate(),0)", userID, totalChange,0,os.time(),itemID)
    else
        sSql = string.format("update UserSkillInfo set Total += %d,LastWriteDate=GetDate() "..
                "where UserID = %d and ItemID = %d;",totalChange,os.time(),userID,itemID)
    end
    SqlServerDataBaseBYExec(sSql)
end