---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/2 16:48
---


Fish = {}
function Fish:New(uid)
    c = {
        FishUID = uid, --UID
        FishKindID = 0, -- 鱼的表中的类型， 是小丑鱼，娃娃鱼，还是锤头鲨
        FishType = 0, -- 鱼大的分类类型， 是大鱼，小鱼，中鱼，还是boss

        DeadTime = 0, -- 过期时间
        PathID = 0, -- 路径
        --pathIndex int		-- 路径索引
        OffsetX = 0,
        OffsetY = 0,
        Speed = 0,
        --
        Mulriple = 0, -- 倍率
        CapturePro = 0, -- 捕获率
        --
        CreateTime = 0, -- 创建时间
        TotalAliveTime = 0, -- 存活时间，秒
        --MovePerPointTime time.Time	-- 移动一个坐标点需要的时间
    }
    setmetatable(c, self)
    self.__index = self
    return c
end

function Fish:Reload(c)
    setmetatable(c, self)
    self.__index = self

    -- 如果热更新有改动成员变量的定义的话， 下面需要进行成员变量的处理
    -- 比如 1 增加了字段， 那么你需要将老数据进行， 新字段的初始化
    -- 比如 2 删除了字段， 那么你需要将老数据进行， 老字段=nil
    -- 比如 3 修改了字段， 那么你需要将老数据进行， 老字段=nil， 新字段初始化或者进行赋值处理
end

--function Fish:FishRun(now,table)
--    if now > self.DeadTime then
--        --print("鱼生存时间到了",self.FishUID)
--        table:DelFish(self.FishUID)
--    end
--
--end
