---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/27 10:19
---


--------------------------------------------------------------------------------
----------------------桌子逻辑关于 玩家 的处理----------------------------------
--------------------------------------------------------------------------------

--获取桌子的所有玩家-
--function ByTable:GetUsersSeatInTable()
--    local userList = {}
--    for i=1,BY_TABLE_MAX_PLAYER do
--        if self.UserSeatArray[i] ~= nil then
--            -- 说明有人在座位上
--            table.insert(userList,self.UserSeatArray[i])
--        end
--    end
--    return userList     -- 元素是player对象
--end
----玩家离开椅子
function ByTable:PlayerStandUp(seatID,player)
    Logger(player.User.UserID.."离开桌子"..player.TableID.."椅子"..player.ChairID)
    -- 调用基类的起立
    self.super.PlayerStandUp(self, seatID, player)
    -- 清理掉玩家所有子弹
    self:DelBullets(player.User.UserID)
    --如果是空桌子的话，清理一下桌子
    if self:CheckTableEmpty() then
        self:ClearTable()
        game:ReleaseTableByUID(self.TableID)    --回收桌子
    end
end

-----清理桌子
function ByTable:ClearTable()
    -- 清理一下生成鱼的结构
    self.DistributeArray = {}
    self.BossDistributeArray = {}

    -- 清理掉所有子弹和鱼群
    self:DelBullets(-1)
    self:DelFishes()

    self.BulletArray = {}
    self.FishArray = {}
    self.UserSeatArray = {}     --  seatID    player

end
