---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/6 10:53
---


--- 各种类型鱼的定义
require("mgby_fish_sever")
require("tb_common")

FishServerExcel = mgby_fish_sever.mgby_fish_sever
TBCommonExcel = tb_common.tb_common

-- excel 获取数据
function GetExcelValue(excel,index,key)
    return excel[tostring(index)][tostring(key)]
end