---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/28 14:27
---

--------------------------------哈希---------------------------------------
----------------------------保存-----------------------------
function RedisSaveString(dir,key,value)
    return luaCallGoRedisSaveString(dir,key,value)
end
----------------------------获取-----------------------------
function RedisGetString(dir,key)
    return luaCallGoRedisGetString(dir,key)     -- 这里返回的都是string，其他格式要自己转一下
end
----------------------------删除-----------------------------
function RedisDelKey(dir,key)
    luaCallGoRedisDelKey(dir,key)
end

----------------------------分布式的数字协调，避免加分布式锁， 可广泛用于多个进程高并发同时处理同一个数据， 保证数据的原子性----------------------------
function RedisRunLuaScript(redis_lua_str, errorLogName)      -- errorLogName 是如果出错的时候，报警用的定位函数名
    return luaCallGoRedisRunLuaScript(redis_lua_str, errorLogName)
end


----------------------------------List-----------------------------------------
function RedisAddList(dir,value)
    return luaCallGoRedisAddList(dir,value)     -- 这里返回的都是string，其他格式要自己转一下
end
function RedisGetList(dir)
    return luaCallGoRedisGetList(dir)     -- 这里返回的都是string，其他格式要自己转一下
end

function RedisDelList(dir,value)
    return luaCallGoRedisDelList(dir,value)     -- 这里返回的都是string，其他格式要自己转一下
end
function RedisDelLast(dir)
    return luaCallGoRedisDelLast(dir)
end