---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.
--- DateTime: 2019/11/5 13:24
---
----------------------------------------------------------------------
--- 登录服的消息处理
----------------------------------------------------------------------
function ChatServerLogic:HandlerLoginServerAction(serverId, userId, subMsgId, data, token)
    if subMsgId == SUB_SC_REGISTER then
        self:LSSubRegisterAction(serverId, userId, data, token)   -- 登录服连接注册
    elseif subMsgId == SUB_SC_PUSH_TOKEN  then
        self:LSSubPushTokonAction(serverId, userId, data, token)  -- 玩家登录成功登录服推送token
    elseif subMsgId == SUB_SC_UPDATE_USER_INFO  then
        self:LSSubUpdateUserInfoAction(serverId, userId, data, token)  -- 玩家登录成功登录服推送token
    elseif subMsgId == SUB_SC_TOKEN_USER_INFO  then
        self:LSSubTokenServerAction(serverId, userId, data, token)  -- 玩家登录成功登录服推送token
    end
end