---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/12 14:57
---

---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------
--- go 来创建和调用的通用代码处理模块， 用来处理世界boss，排行榜，各种公开活动
---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------


--公共逻辑循环处理
function GoCallLuaCommonLogicRun()
--    print("公共逻辑循环处理")
    ShowAllGameStates()
end

-- 每60秒记录一下，服务器的状态到数据库中
function GoCallLuaSaveServerState()
    local tableNum = 0
    local playerNum = 0
    for k, v in pairs(AllGamesList) do
        local game = GetGameByID(k)
        --print("游戏"..k.."有桌子数量"..GetTableLen(game.AllTableList)..",有玩家数量"..GetTableLen(AllPlayerList))
        tableNum = tableNum + GetTableLen(game.AllTableList)
    end
    local state = {}
    state["Tables"] = tableNum
    state["Players"] = GetTableLen(AllPlayerList)
    RedisSaveServerState(state)
end


--夜里12点触发公共逻辑变动，因为新的一天开始了
function GoCallLuaCommonLogic12clock()
    print("夜里12点触发公共逻辑变动，因为新的一天开始了")
end


