---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.
--- DateTime: 2019/4/12 13:43
---


--------------------桌面剩余金币--------------------------------

-- 获取桌面剩余金币数量
function CoinGetRemainTableGold(player)
    if player.GameType == GameTypeTB10 then
        return player.User.GoldRemainTable10
    elseif player.GameType == GameTypeTB100 then
        return player.User.GoldRemainTable100
    elseif player.GameType == GameTypeTB1000 then
        return player.User.GoldRemainTable1000
    elseif player.GameType == GameTypeTB10000 then
        return player.User.GoldRemainTable10000
    end
end

-- 增加桌面剩余金币数量
function CoinAddRemainTableGold(player,value)
    if player.GameType == GameTypeTB10 then
        player.User.GoldRemainTable10 = player.User.GoldRemainTable10 + value
    elseif player.GameType == GameTypeTB100 then
        player.User.GoldRemainTable100 = player.User.GoldRemainTable100 + value
    elseif player.GameType == GameTypeTB1000 then
        player.User.GoldRemainTable1000 = player.User.GoldRemainTable1000 + value
    elseif player.GameType == GameTypeTB10000 then
        player.User.GoldRemainTable10000 = player.User.GoldRemainTable10000 + value
    end

end

-- 减少桌面剩余金币数量
function CoinReduceRemainTableGold(player,value)
    if player.GameType == GameTypeTB10 then
        player.User.GoldRemainTable10 = player.User.GoldRemainTable10 - value
    elseif player.GameType == GameTypeTB100 then
        player.User.GoldRemainTable100 = player.User.GoldRemainTable100 - value
    elseif player.GameType == GameTypeTB1000 then
        player.User.GoldRemainTable1000 = player.User.GoldRemainTable1000 - value
    elseif player.GameType == GameTypeTB10000 then
        player.User.GoldRemainTable10000 = player.User.GoldRemainTable10000 - value
    end

end



---------------------------小金币--------------------------------------------------


function CoinCreateNewGold(sendCmd, coinNumber, player)
    print("生成小金币--------------------------------------------- "..coinNumber)
    local gameTable = player:GetTable()
    local dwUID, cbType, lottery_value

    -- 奖券的随机出现， 小金币
    if gameTable.cbCloseLottery == 0 and player.User.cbConfineLottery == 0 then
        -- 没有关闭奖券 ，玩家也没有被限制获得奖券
        dwUID, cbType, lottery_value = LotteryGetSpCoin(player, coinNumber)    -- 随机奖券
        -- 是奖券
        if cbType ~= COIN_TYPE_NORMAL then
            -- 增加到协议中
            local coin = sendCmd.coin_data:add()
            coin.coin_uid = dwUID
            coin.lottery_type = cbType
            coin.lottery_value = lottery_value

            CoinAddRemainTableGold(player,1)        -- 桌面增加奖券的数量 ，这个地方有点恶心，以后让客户端把奖券和普通金币分开最好
        end
    end

    -- 台面剩余金币增加
    CoinAddRemainTableGold(player, coinNumber)     -- 小金币导致桌面金币数量增加

    -- 个人库存减少 -- 全局库存减少
    PoolReducePersonAndAll(player, coinNumber)

    -- 判断小奖池积分赛
    PointCheckGetPoints(player,coinNumber)

    return sendCmd , lottery_value

end


