---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.
--- DateTime: 2019/4/20 17:41
---

----------------------------------------------------------------------------------
--- 轮盘  只掉大金币
----------------------------------------------------------------------------------

--轮盘掉大金币，这里主要是类型不同
function WheelCalcCreateCoin_Roulette(bigCoinNumber, player, sendCmd, wheelType)
    local bigCoinType = wheelType + BIG_COIN_TYPE_0    -- 因为轮盘的大金币编号在老虎机后面， 所以加上一个偏移量
    return CoinCreateNewBigGold(bigCoinNumber, player, sendCmd, bigCoinType)

end





-- 计算轮盘的几率
function WheelCalcPlateWinPro()
    local rand = GetRandom(1,10000)
    for i=1,8 do
        local rate = GetExcelValue(TBWheelExcel,i,"rate")
        if rand <= rate then
            -- 就是这个档位了
            local wheelType = GetExcelValue(TBWheelExcel,i,"result")
            local wheelMulti = GetExcelValue(TBWheelExcel,i,"multi")
            return  wheelType ,wheelMulti
        end
    end
    print("没有找到轮盘几率的档位。。。。。。。。。。。。。。。。。。。")
end



-- 轮盘的奖励
function WheelGetGoldReward(player)
    return player.m_dwRouletteCurReward
end
function WheelAddGoldReward(player, reward)
    player.m_dwRouletteCurReward = player.m_dwRouletteCurReward + reward
end

function WheelClearGoldReward(player)
    player.m_dwRouletteCurReward = 0
end

-- 轮盘的次数
function WheelGetDoubleTimes(player)
    return player.m_wRouletteDoubleTimes
end

function WheelReduceDoubleTimes(player)
    player.m_wRouletteDoubleTimes = player.m_wRouletteDoubleTimes - 1
end

function WheelClearDoubleTimes(player)
    player.m_wRouletteDoubleTimes = 0
end

--