---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1 10:54
---

------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
--- 游戏管理器， 管理很多游戏， 每个游戏再去管理自己的房间和玩家
--- 新添加游戏步骤：1, 定义类型  2 AddGame  3 在games.lua里面定义根据不同的游戏定义不同的房间 4 创建一个新游戏的房间.lua文件
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------

GameServer = {}


--增加一个游戏， 指定这个游戏的类型， 并且创建一个房间，并启动房间逻辑
local function addGame(name, gameType)
    if GameServer.GetGameByID(gameType) ~= nil then
        ZLog.Logger("游戏类型["..gameType.."已经添加过了，不用重复添加")
        return
    end

    local game = Game:New(name, gameType)
    -- 加入到游戏总列表中
    GameServer.SetAllGamesList(gameType, game)

    --Logger("--------------AddGame--------------------------")
    Game.CreateRoom(game, gameType)
    --game.GameScore = gameScore
end

-- 游戏服务器入口点
function GameServer.Start()
    --Logger("--------------------注册中心服----------------------------")
    --ServerMainServer = LuaNetWorkConnectOtherServer(Setting.ConstMainCenterServer)  -- 申请连接协调服务器，并 把serverId保存下来， 以后发送消息用
    --print("协调服 serverId ",ServerMainServer)

    print("-------------------  添加主循环  ------------------------------")
    ZTimer.SetNewTimer("GameServer", "RunGamesRooms", 200, GameServer.RunGamesRooms)

    print("-------------------  添加游戏  ------------------------------")
    addGame("沙石镇", Const.GameTypeCCC)

    --addGame("满贯捕鱼", GameTypeBY , 1)           -- 普通房间
    --addGame("满贯捕鱼30倍", GameTypeBY30 , 30)    -- 30倍房间
    --addGame("满贯捕鱼2", GameTypeBY2)
    --addGame("满贯捕鱼3", GameTypeBY3)
    --addGame("小海兽", GameTypeXHS, 1)

    --SetNewTimer("NewTimerBy2Second",2 * 1000)      -- lua 自己设定计时器
    --SetNewClockTimer("NewTimerByAfternoon4", 16)    -- lua 自己设定的固定时间定时器，  16:00

    --Logger("--------------------注册协调服----------------------------")
    --ServerIDofCorrespondServer = LuaNetWorkConnectOtherServer(ConstServerAddressCorrespondServer)  -- 申请连接协调服务器，并 把serverId保存下来， 以后发送消息用
    --print("协调服 serverId ",ServerIDofCorrespondServer)
    --Logger("--------------------注册日志服----------------------------")

    --ServerIDofLogServer = LuaNetWorkConnectOtherServer(ConstServerAddressLogServer)                 -- 申请连接服务器，并 把serverId保存下来， 以后发送消息用
    --print("日志服 serverId ",ServerIDofLogServer)

    --Logger("--------------StartGamesServers  End--------------------------")
    --Logger("ServerIP_Port:"..ServerIP_Port)

end

-----------------------------------玩家注册，玩家掉线-------------------------------------


local RedisDirAllPlayersUUID          = "CCC:AllPlayers_UUID:"                         -- 所有玩家UUID
----------------------------多进程申请UUID信息， 会执行脚本先增加，然后把最新的数字返回-----------------------------
local function GetAllPlayersUUID(num)
    --return RedisAddNumber(RedisDirAllPlayersUUID.."BY_UUID" ,"BY_UUID",num)
    local dir = RedisDirAllPlayersUUID.."CCC_UUID"
    local key = "CCC_UUID"
    local redis_lua_str = [[
    local r = redis.call('hget',"%s","%s")
       if r ~= false then
            r = r + %d
       else
            r = 1000000001
       end
    redis.call('hset',"%s","%s", r)
    return r
    ]]
    redis_lua_str = string.format(redis_lua_str,dir,key, num, dir,key)
    return Redis.RunLuaScript(redis_lua_str, "RedisMultiProcessGetAllPlayersUUID")
end

--有一个新的玩家注册了，那么给他分配一个UID
function GameServer.GetLastUserID()
    local r = 1     -- math.random(1, 4)        --返回[1,4]的随机整数
    local uuid = GetAllPlayersUUID(r)     -- 分布式申请UUID
    --Logger("给玩家分配新uid  ALLUserUUID "..uuid)
    return uuid
end


-- 根据user uid 返回user的句柄
function GameServer.GetPlayerByUID(uid)
    return GlobalVar.AllPlayerList[tostring(uid)]
end

function GameServer.SetAllPlayerList(userId, value)
    GlobalVar.AllPlayerList[tostring(userId)] = value
    if value == nil then
        GlobalVar.AllPlayerListNumber = GlobalVar.AllPlayerListNumber - 1   -- 玩家人数减少
    else
        GlobalVar.AllPlayerListNumber = GlobalVar.AllPlayerListNumber + 1   -- 玩家人数增加
    end
end


-----------------------------------游戏-------------------------------------


--通过gameID获取是哪个游戏
function GameServer.GetGameByID(gameType)
    return GlobalVar.AllGamesList[tostring(gameType)]
end

function GameServer.SetAllGamesList(gameType, value)
    GlobalVar.AllGamesList[tostring(gameType)] = value
end

-----------------------------------房间-------------------------------------
---- 显示当前的状态
--function ShowAllGameStates()
--    for gameType, game in pairs(GlobalVar.AllGamesList) do
--        --local game = GetGameByID(k)
--        --print("游戏"..gameType.."有房间数量"..game.AllTableListNumber..",有玩家数量".. AllPlayerListNumber)
--    end
--end



-- 遍历所有的列表，然后依次run,  改为服务器自己创建定时器处理
function GameServer.RunGamesRooms()
    for _, game in pairs(GlobalVar.AllGamesList) do
        for _, room in pairs(game.AllRoomList) do
            room:RunRoom() -- 执行注册的函数，table run
        end
    end
end
