---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/5 14:07
---


--- 客户端用来统计消息传递的时间
function HandleStaticsNetWorkTime(UserId)
    LuaNetWorkSendToUser(UserId,MDM_GF_GAME, SUB_S_BOSS_COME,nil,nil)
end