---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/1 14:34
---

-------------------------------------说明----------------------------------------
---本文件是服务器启动的时候加载使用
-----------------------------------------------------------------------------


-------------------------------------CSV----------------------------------------
--package.path = "Script/CSV/?.lua;"..package.path
--data_csv1 = require("mgby_fish_sever")
--print(data_csv1[134].type)
--print(data_csv1[134].min_force_killed_bullet)
--Logger("csv ok")

-------------------------------------protocol buffer----------------------------------------
package.path = "Script/Protocol/build/?.lua;"..package.path
package.path = "Script/Protocol/protobuf/?.lua;"..package.path
--require("protocol_test")
--Logger("protocol buffer ok")

-------------------------------------Const----------------------------------------
-- 这部分不参与热更新
require("Script/Utils/string/json")                 -- Json
require("Script/Utils/string/zStrings")                 -- strings
require("Script/Utils/byte/zCrypto")
require("Script/Utils/byte/zBit32")
require("Script/Utils/byte/zZip")
require("Script/GlobalVar/globalVar")

-------------------------------------Start----------------------------------------
-- 下面参与热更新，新增加lua文件， 写到reload里面去，不要在这里添加
require("Script/HotReload/hotReload")

-- CSV
for _,fileName in ipairs(RequireAndReloadCSVFiles) do
    require(fileName)
end

-- Protocol
for _,fileName in ipairs(RequireAndReloadProtocolFiles) do
    require(fileName)
end

-- Const
for _,fileName in ipairs(RequireAndReloadConstFiles) do
    require(fileName)
end

-- Utils
for _,fileName in ipairs(RequireAndReloadUtilsFiles) do
    require(fileName)
end

-- DataBase
for _,fileName in ipairs(RequireAndReloadDataBaseFiles) do
    require(fileName)
end


-- Games
for _,fileName in ipairs(RequireAndReloadGamesFiles) do
    require(fileName)
end

-- GameManager
for _,fileName in ipairs(RequireAndReloadManagerFiles) do
    require(fileName)
end


-- NetWork
for _,fileName in ipairs(RequireAndReloadNetWorkFiles) do
    require(fileName)
end

---  chatServer 聊天服
for _,fileName in ipairs(RequireAndReloadChatServerFiles) do
    require(fileName)
end



--
--
---------------------------------------Const----------------------------------------
--require("commonLogic")
--require("hotReload")
--require("Time")
--require("Random")
--require("dumpTable")
--require("zTable")
--require("redis")
--require("luaMySql")
--require("luaSqlServer")
--require("zMySql")
--MySerpent = require("serpent")
---------------------------------------Redis mySql----------------------------------------
--package.path = "Script/DataBase/?.lua;"..package.path
--require("redisConst")
--require("redisGame")
--require("redisPlayer")
--require("sqlStatistic")
--
--
----Logger("system ok")
---------------------------------------NetWork----------------------------------------
--
----require("multiThreadChannel")
--require("gameFire")
--require("gameEnter")
--require("LoginServer")
--require("Statistic")
--require("network")
--
---------------------------------------GameManager----------------------------------------
--
--require("globalVar")
--require("player")
--require("user")
--
--package.path = "Script/Games/BY/?.lua;"..package.path
--require("byBullet")
--require("byFish")
--require("byFishDistribute")
--require("byTable")
--require("byTableFishFunc")
--require("byTableBulletFunc")
--require("byTablePlayerFunc")
--
--require("games")
--require("gameManager")