---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by soonyo.zhengxh
--- DateTime: 2019/10/18 17:50
---


-- 功能:ChatServer注册协调服
function ChatServerRegisterCorrespondServer()
    --Logger("正在注册游戏ChatServer...ServerIDofCorrespondServer="..ServerIDofCorrespondServer)
    local sendMsg = CMD_GlobalServer_Inner_pb.CMD_CS_C_RegisterChat();
    sendMsg.szServerName = "goLua聊天服";
    sendMsg.szServerAddr = ConstServerAddressChatServer;
    local bSend =  LuaNetWorkSend( ServerIDofCorrespondServer, MDM_CS_REGISTER, SUB_CS_C_REGISTER_CHAT , sendMsg,nil);
    Logger(string.format("ChatServerRegisterCorrespondServer:发送注册聊天服的消息：bSend=%s",tostring(bSend)));

end


-- 功能:GameServer注册协调服
function GameServerRegisterCorrespondServer()
    -- 遍历所有游戏并注册到协调服
    local tbServerInfo = StringSplitToStringArray(ServerIP_Port,":")
    for gameType, game in pairs(AllGamesList) do
        local sendMsg = CMD_GlobalServer_Inner_pb.CMD_CS_C_RegisterServer()
        local gameRoomInfo = game.GameRoomInfo
        sendMsg.serverInfo.wKindID              = gameRoomInfo.GameID
        sendMsg.serverInfo.wNodeID              = gameRoomInfo.NodeID
        sendMsg.serverInfo.wSortID              = gameRoomInfo.SortID
        sendMsg.serverInfo.wServerID            = gameRoomInfo.ServerID
        sendMsg.serverInfo.wServerPort          = tonumber(tbServerInfo[2])
        sendMsg.serverInfo.dwOnLineCount        = 0
        sendMsg.serverInfo.lCellScore           = game.GameScore
        sendMsg.serverInfo.llMinEnterScore      = gameRoomInfo.MinEnterScore
        sendMsg.serverInfo.llMaxEnterScore      = gameRoomInfo.MaxEnterScore
        sendMsg.serverInfo.cbMinEnterVipLev     = gameRoomInfo.MinEnterVip
        sendMsg.serverInfo.cbMinEnterCannonLev  = gameRoomInfo.MinEnterCannonLev
        sendMsg.serverInfo.cbMaxEnterCannonLev  = gameRoomInfo.MaxEnterCannonLev
        sendMsg.serverInfo.dwServerType         = gameRoomInfo.ServerType
        sendMsg.serverInfo.llServerRule         = gameRoomInfo.ServerRule
        sendMsg.serverInfo.nServerAddrNum       = 3
        sendMsg.serverInfo.szServerName         = game.Name
        for i = 1, 10 do
            local addInfo = sendMsg.serverInfo.arrServerAddr:add()
            if i == 1 then
                addInfo.iType = 0
                addInfo.szAddress = tbServerInfo[1]
            else
                addInfo.iType = 0
                addInfo.szAddress = ""
            end
        end
        for i = 1, 10 do
            if i == 1 then
                sendMsg.serverInfo.aServerVersion:append(210)
            end
            sendMsg.serverInfo.aServerVersion:append(0)
        end

        LuaNetWorkSend( ServerIDofCorrespondServer, MDM_CS_REGISTER, SUB_CS_C_REGISTER_SERVER , sendMsg,nil)

    end

    print(string.format("发送服务器注册到协调服消息MainCMD:%d,SubCMD:%d",MDM_CS_REGISTER,SUB_CS_C_REGISTER_SERVER))
end