---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhushiwei.
--- DateTime: 2020/12/8 14:13
---
CMD_MAIN= {
    -- 注册命令(MainCmd)
    MDM_SERVER = 1  ,    -- 服务器命令
    MDM_GAME_CCC = 2    ,    -- ccc游戏命令

}






MDM_GR_CONFIG = 2  --# 配置命令
MDM_GR_USER = 3  --# 用户命令
MDM_GR_STATUS = 4  --# 状态命令
MDM_GR_MANAGE = 5  --# 管理命令
MDM_GF_FRAME = 6  --# 框架命令
MDM_GF_GAME = 7  --# 框架游戏命令
MDM_CR_SYSTEM = 8  --# 系统命令
MDM_GR_ONLINE_CHECK = 9  --# 在线检测
MDM_GR_PURCHASE = 10 --# 充值命令
MDM_GR_BIND = 11 --# 手机绑定
MDM_GR_HEARTBEAT = 12 --# 心跳
MDM_GR_VIP = 13 --# VIP
MDM_GR_REWARD = 14 --# 奖励命令
MDM_GR_MATCH = 15 --# 比赛
MDM_GR_MISSION = 16 --# 任务
MDM_GR_ACHIEVEMENT_TITLE = 17 --# 称号
MDM_GR_GUILD = 18 --# 公会
MDM_GF_GMCMD = 19 --# GM指令

