module = {
[1] = {  age = 10,  man = true,  },
[2] = {  age = 11,  man = true,  },
[3] = {  age = 12,  man = true,  },
[4] = {  age = 13,  man = true,  },
[5] = {  age = 14,  man = true,  },
[6] = {  age = 15,  man = true,  },
[7] = {  age = 16.44,  man = true,  },
[8] = {  age = 17,  man = true,  },
[9] = {  age = 18,  man = true,  },
[10] = {  age = 19,  man = true,  },
[11] = {  age = 20,  man = true,  },
[12] = {  age = 21,  man = true,  },
[13] = {  age = 22,  man = true,  },
[14] = {  age = 23,  man = true,  },
[15] = {  age = 24,  man = true,  },
[16] = {  age = 25,  man = true,  },
[17] = {  age = 26,  man = true,  },
[18] = {  age = 27,  man = false,  },
[19] = {  age = 28,  man = true,  },
[20] = {  age = 29,  man = false,  },
} 
 return module