module = {
["1"] = {  name = "xx",  age = 10,  man = true,  },
["2"] = {  name = "xx1",  age = 11,  man = true,  },
["3"] = {  name = "xx2",  age = 12,  man = true,  },
["4"] = {  name = "xx3",  age = 13,  man = true,  },
["5"] = {  name = "xx4",  age = 14,  man = true,  },
["6"] = {  name = "xx5",  age = 15,  man = true,  },
["7"] = {  name = "xx6",  age = 16.44,  man = true,  },
["8"] = {  name = "xx7",  age = 17,  man = true,  },
["9"] = {  name = "xx8",  age = 18,  man = true,  },
["10"] = {  name = "xx9",  age = 19,  man = true,  },
["11"] = {  name = "xx10",  age = 20,  man = true,  },
["12"] = {  name = "xx11",  age = 21,  man = true,  },
["13"] = {  name = "xx12",  age = 22,  man = true,  },
["14"] = {  name = "xx13",  age = 23,  man = true,  },
["15"] = {  name = "xx14",  age = 24,  man = true,  },
["16"] = {  name = "xx15",  age = 25,  man = true,  },
["17"] = {  name = "xx16",  age = 26,  man = true,  },
["18"] = {  name = "xx17",  age = 27,  man = false,  },
["19"] = {  name = "xx18",  age = 28,  man = true,  },
["20"] = {  name = "xx19",  age = 29,  man = false,  },
} 
 return module