---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/12 14:52
---

ZLog={}
function ZLog.Logger(str)
    luaCallGoPrintLogger(str)
end



function ZLog.printTable1(table)
    printTable(table)
end