// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CMD_FQZS_Game.CMD

/*
Package CMD is a generated protocol buffer package.

Namespace: MESSAGE

It is generated from these files:
	CMD_FQZS_Game.CMD

It has these top-level messages:
	CMD_SUB_C_REQ_BANKER
	CMD_SUB_S_REQ_BANKER
	CMD_Userinfo_S
	CMD_UserChip_ST
	CMD_Sence_Free
	CMD_GameStart_S
	CMD_GameEnd_Info_S
	CMD_UpdataChip_S
	CMD_SysMessage_S
	CMD_Gameinfo_S
	CMD_GameOpenLog_S
	CMD_Control_UserLeave_S
	CMD_Control_DealRet_S
	CMD_GameResultinfo_S
	CMD_Control_Update_S
	CMD_ChipSucc_S
	CMD_ClearUserChip_S
	CMD_ContinueChipResult_S
	CMD_SelfResult_S
	CMD_UpdateSelfScore_S
	CMD_Control_UserInfo_S
	CMD_Control_StockInfo_S
	CMD_Control_UserChip_S
	CMD_UserChipNotify_S
	CMD_UserContinue_ChipNotify_S
	CMD_ReqBanker_Result
	CMD_WaitBankerUserInfo
	CMD_BankerUserInfo
	CMD_BankerResult_S
	CMD_EMPTY_MESSAGE_S
	CMD_Control_SelectDst_C
	CMD_UserChip_C
	CMD_UserContinueChip_C
	CMD_Control_SetDst_C
	CMD_ReqBanker_C
	CMD_Control_UserTotalChipInfo_S
	CMD_SUB_C_ONLINE_TOTAL
	CMD_SUB_S_ONLINE_TOTAL
	CMD_SUB_C_ROBBANK
	CMD_SUB_S_AndroidUpdateChip
*/
package CMD

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the CMD package it is being compiled against.
// A compilation error at this line likely means your copy of the
// CMD package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the CMD package

// 请求上庄
type CMD_SUB_C_REQ_BANKER struct {
	ReqType          *int32 `protobuf:"varint,1,opt,name=req_type,json=reqType" json:"req_type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_SUB_C_REQ_BANKER) Reset()                    { *m = CMD_SUB_C_REQ_BANKER{} }
func (m *CMD_SUB_C_REQ_BANKER) String() string            { return proto.CompactTextString(m) }
func (*CMD_SUB_C_REQ_BANKER) ProtoMessage()               {}
func (*CMD_SUB_C_REQ_BANKER) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CMD_SUB_C_REQ_BANKER) GetReqType() int32 {
	if m != nil && m.ReqType != nil {
		return *m.ReqType
	}
	return 0
}

type CMD_SUB_S_REQ_BANKER struct {
	ReqResultInfo    []byte `protobuf:"bytes,1,opt,name=req_result_info,json=reqResultInfo" json:"req_result_info,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_SUB_S_REQ_BANKER) Reset()                    { *m = CMD_SUB_S_REQ_BANKER{} }
func (m *CMD_SUB_S_REQ_BANKER) String() string            { return proto.CompactTextString(m) }
func (*CMD_SUB_S_REQ_BANKER) ProtoMessage()               {}
func (*CMD_SUB_S_REQ_BANKER) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CMD_SUB_S_REQ_BANKER) GetReqResultInfo() []byte {
	if m != nil {
		return m.ReqResultInfo
	}
	return nil
}

type CMD_Userinfo_S struct {
	UserScore          *int64   `protobuf:"varint,1,opt,name=user_score,json=userScore" json:"user_score,omitempty"`
	NickName           []byte   `protobuf:"bytes,2,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	ChipValue          []uint32 `protobuf:"varint,3,rep,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	BankerScoreRequest *int64   `protobuf:"varint,4,opt,name=banker_score_request,json=bankerScoreRequest" json:"banker_score_request,omitempty"`
	ChipUpLimit        *int32   `protobuf:"varint,5,opt,name=chip_up_limit,json=chipUpLimit" json:"chip_up_limit,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *CMD_Userinfo_S) Reset()                    { *m = CMD_Userinfo_S{} }
func (m *CMD_Userinfo_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Userinfo_S) ProtoMessage()               {}
func (*CMD_Userinfo_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CMD_Userinfo_S) GetUserScore() int64 {
	if m != nil && m.UserScore != nil {
		return *m.UserScore
	}
	return 0
}

func (m *CMD_Userinfo_S) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *CMD_Userinfo_S) GetChipValue() []uint32 {
	if m != nil {
		return m.ChipValue
	}
	return nil
}

func (m *CMD_Userinfo_S) GetBankerScoreRequest() int64 {
	if m != nil && m.BankerScoreRequest != nil {
		return *m.BankerScoreRequest
	}
	return 0
}

func (m *CMD_Userinfo_S) GetChipUpLimit() int32 {
	if m != nil && m.ChipUpLimit != nil {
		return *m.ChipUpLimit
	}
	return 0
}

type CMD_UserChip_ST struct {
	UserChip         []int64 `protobuf:"varint,1,rep,name=user_chip,json=userChip" json:"user_chip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_UserChip_ST) Reset()                    { *m = CMD_UserChip_ST{} }
func (m *CMD_UserChip_ST) String() string            { return proto.CompactTextString(m) }
func (*CMD_UserChip_ST) ProtoMessage()               {}
func (*CMD_UserChip_ST) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CMD_UserChip_ST) GetUserChip() []int64 {
	if m != nil {
		return m.UserChip
	}
	return nil
}

type CMD_Sence_Free struct {
	GameStatus       *uint32          `protobuf:"varint,1,opt,name=game_status,json=gameStatus" json:"game_status,omitempty"`
	UserScore        *int64           `protobuf:"varint,2,opt,name=user_score,json=userScore" json:"user_score,omitempty"`
	UserChip         *CMD_UserChip_ST `protobuf:"bytes,3,opt,name=user_chip,json=userChip" json:"user_chip,omitempty"`
	AllUserChip      *CMD_UserChip_ST `protobuf:"bytes,4,opt,name=all_user_chip,json=allUserChip" json:"all_user_chip,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CMD_Sence_Free) Reset()                    { *m = CMD_Sence_Free{} }
func (m *CMD_Sence_Free) String() string            { return proto.CompactTextString(m) }
func (*CMD_Sence_Free) ProtoMessage()               {}
func (*CMD_Sence_Free) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CMD_Sence_Free) GetGameStatus() uint32 {
	if m != nil && m.GameStatus != nil {
		return *m.GameStatus
	}
	return 0
}

func (m *CMD_Sence_Free) GetUserScore() int64 {
	if m != nil && m.UserScore != nil {
		return *m.UserScore
	}
	return 0
}

func (m *CMD_Sence_Free) GetUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.UserChip
	}
	return nil
}

func (m *CMD_Sence_Free) GetAllUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.AllUserChip
	}
	return nil
}

type CMD_GameStart_S struct {
	DstType          *uint32 `protobuf:"varint,1,opt,name=dst_type,json=dstType" json:"dst_type,omitempty"`
	DstIndex         *uint32 `protobuf:"varint,2,opt,name=dst_index,json=dstIndex" json:"dst_index,omitempty"`
	LastPos          *uint32 `protobuf:"varint,3,opt,name=last_pos,json=lastPos" json:"last_pos,omitempty"`
	DstPos           *uint32 `protobuf:"varint,4,opt,name=dst_pos,json=dstPos" json:"dst_pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_GameStart_S) Reset()                    { *m = CMD_GameStart_S{} }
func (m *CMD_GameStart_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_GameStart_S) ProtoMessage()               {}
func (*CMD_GameStart_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CMD_GameStart_S) GetDstType() uint32 {
	if m != nil && m.DstType != nil {
		return *m.DstType
	}
	return 0
}

func (m *CMD_GameStart_S) GetDstIndex() uint32 {
	if m != nil && m.DstIndex != nil {
		return *m.DstIndex
	}
	return 0
}

func (m *CMD_GameStart_S) GetLastPos() uint32 {
	if m != nil && m.LastPos != nil {
		return *m.LastPos
	}
	return 0
}

func (m *CMD_GameStart_S) GetDstPos() uint32 {
	if m != nil && m.DstPos != nil {
		return *m.DstPos
	}
	return 0
}

type CMD_GameEnd_Info_S struct {
	BankerUserid     *uint32  `protobuf:"varint,1,opt,name=banker_userid,json=bankerUserid" json:"banker_userid,omitempty"`
	BankerName       []byte   `protobuf:"bytes,2,opt,name=banker_name,json=bankerName" json:"banker_name,omitempty"`
	BankerWin        *int64   `protobuf:"varint,3,opt,name=banker_win,json=bankerWin" json:"banker_win,omitempty"`
	UserCount        *uint32  `protobuf:"varint,4,opt,name=user_count,json=userCount" json:"user_count,omitempty"`
	NickName         [][]byte `protobuf:"bytes,5,rep,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	UserWin          []int64  `protobuf:"varint,6,rep,name=user_win,json=userWin" json:"user_win,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMD_GameEnd_Info_S) Reset()                    { *m = CMD_GameEnd_Info_S{} }
func (m *CMD_GameEnd_Info_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_GameEnd_Info_S) ProtoMessage()               {}
func (*CMD_GameEnd_Info_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CMD_GameEnd_Info_S) GetBankerUserid() uint32 {
	if m != nil && m.BankerUserid != nil {
		return *m.BankerUserid
	}
	return 0
}

func (m *CMD_GameEnd_Info_S) GetBankerName() []byte {
	if m != nil {
		return m.BankerName
	}
	return nil
}

func (m *CMD_GameEnd_Info_S) GetBankerWin() int64 {
	if m != nil && m.BankerWin != nil {
		return *m.BankerWin
	}
	return 0
}

func (m *CMD_GameEnd_Info_S) GetUserCount() uint32 {
	if m != nil && m.UserCount != nil {
		return *m.UserCount
	}
	return 0
}

func (m *CMD_GameEnd_Info_S) GetNickName() [][]byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *CMD_GameEnd_Info_S) GetUserWin() []int64 {
	if m != nil {
		return m.UserWin
	}
	return nil
}

type CMD_UpdataChip_S struct {
	UserChip         *CMD_UserChip_ST `protobuf:"bytes,1,opt,name=user_chip,json=userChip" json:"user_chip,omitempty"`
	AllServerChip    *CMD_UserChip_ST `protobuf:"bytes,2,opt,name=all_server_chip,json=allServerChip" json:"all_server_chip,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CMD_UpdataChip_S) Reset()                    { *m = CMD_UpdataChip_S{} }
func (m *CMD_UpdataChip_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_UpdataChip_S) ProtoMessage()               {}
func (*CMD_UpdataChip_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CMD_UpdataChip_S) GetUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.UserChip
	}
	return nil
}

func (m *CMD_UpdataChip_S) GetAllServerChip() *CMD_UserChip_ST {
	if m != nil {
		return m.AllServerChip
	}
	return nil
}

type CMD_SysMessage_S struct {
	SysType          *uint32 `protobuf:"varint,1,opt,name=sys_type,json=sysType" json:"sys_type,omitempty"`
	SysMessage       []byte  `protobuf:"bytes,2,opt,name=sys_message,json=sysMessage" json:"sys_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_SysMessage_S) Reset()                    { *m = CMD_SysMessage_S{} }
func (m *CMD_SysMessage_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_SysMessage_S) ProtoMessage()               {}
func (*CMD_SysMessage_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CMD_SysMessage_S) GetSysType() uint32 {
	if m != nil && m.SysType != nil {
		return *m.SysType
	}
	return 0
}

func (m *CMD_SysMessage_S) GetSysMessage() []byte {
	if m != nil {
		return m.SysMessage
	}
	return nil
}

// 游戏的数据
type CMD_Gameinfo_S struct {
	GmaeStatus       *uint32 `protobuf:"varint,1,opt,name=gmae_status,json=gmaeStatus" json:"gmae_status,omitempty"`
	TimerValue       *uint32 `protobuf:"varint,2,opt,name=timer_value,json=timerValue" json:"timer_value,omitempty"`
	Pond             *int64  `protobuf:"varint,3,opt,name=pond" json:"pond,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Gameinfo_S) Reset()                    { *m = CMD_Gameinfo_S{} }
func (m *CMD_Gameinfo_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Gameinfo_S) ProtoMessage()               {}
func (*CMD_Gameinfo_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CMD_Gameinfo_S) GetGmaeStatus() uint32 {
	if m != nil && m.GmaeStatus != nil {
		return *m.GmaeStatus
	}
	return 0
}

func (m *CMD_Gameinfo_S) GetTimerValue() uint32 {
	if m != nil && m.TimerValue != nil {
		return *m.TimerValue
	}
	return 0
}

func (m *CMD_Gameinfo_S) GetPond() int64 {
	if m != nil && m.Pond != nil {
		return *m.Pond
	}
	return 0
}

type CMD_GameOpenLog_S struct {
	ArrCount         *uint32  `protobuf:"varint,1,opt,name=arr_count,json=arrCount" json:"arr_count,omitempty"`
	ArrOpenLog       []uint32 `protobuf:"varint,2,rep,name=arr_open_log,json=arrOpenLog" json:"arr_open_log,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMD_GameOpenLog_S) Reset()                    { *m = CMD_GameOpenLog_S{} }
func (m *CMD_GameOpenLog_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_GameOpenLog_S) ProtoMessage()               {}
func (*CMD_GameOpenLog_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CMD_GameOpenLog_S) GetArrCount() uint32 {
	if m != nil && m.ArrCount != nil {
		return *m.ArrCount
	}
	return 0
}

func (m *CMD_GameOpenLog_S) GetArrOpenLog() []uint32 {
	if m != nil {
		return m.ArrOpenLog
	}
	return nil
}

type CMD_Control_UserLeave_S struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Control_UserLeave_S) Reset()                    { *m = CMD_Control_UserLeave_S{} }
func (m *CMD_Control_UserLeave_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_UserLeave_S) ProtoMessage()               {}
func (*CMD_Control_UserLeave_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CMD_Control_UserLeave_S) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type CMD_Control_DealRet_S struct {
	Ret              *uint32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	ResultDes        []byte  `protobuf:"bytes,2,opt,name=result_des,json=resultDes" json:"result_des,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Control_DealRet_S) Reset()                    { *m = CMD_Control_DealRet_S{} }
func (m *CMD_Control_DealRet_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_DealRet_S) ProtoMessage()               {}
func (*CMD_Control_DealRet_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CMD_Control_DealRet_S) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *CMD_Control_DealRet_S) GetResultDes() []byte {
	if m != nil {
		return m.ResultDes
	}
	return nil
}

// 游戏的结算信息
type CMD_GameResultinfo_S struct {
	WinScoreChange   *int64 `protobuf:"varint,1,opt,name=win_score_change,json=winScoreChange" json:"win_score_change,omitempty"`
	ChipValue        *int64 `protobuf:"varint,2,opt,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	NewScore         *int64 `protobuf:"varint,3,opt,name=new_score,json=newScore" json:"new_score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_GameResultinfo_S) Reset()                    { *m = CMD_GameResultinfo_S{} }
func (m *CMD_GameResultinfo_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_GameResultinfo_S) ProtoMessage()               {}
func (*CMD_GameResultinfo_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CMD_GameResultinfo_S) GetWinScoreChange() int64 {
	if m != nil && m.WinScoreChange != nil {
		return *m.WinScoreChange
	}
	return 0
}

func (m *CMD_GameResultinfo_S) GetChipValue() int64 {
	if m != nil && m.ChipValue != nil {
		return *m.ChipValue
	}
	return 0
}

func (m *CMD_GameResultinfo_S) GetNewScore() int64 {
	if m != nil && m.NewScore != nil {
		return *m.NewScore
	}
	return 0
}

type CMD_Control_Update_S struct {
	RealUserChip     *CMD_UserChip_ST `protobuf:"bytes,1,opt,name=real_user_chip,json=realUserChip" json:"real_user_chip,omitempty"`
	DstUserChip      *CMD_UserChip_ST `protobuf:"bytes,2,opt,name=dst_user_chip,json=dstUserChip" json:"dst_user_chip,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CMD_Control_Update_S) Reset()                    { *m = CMD_Control_Update_S{} }
func (m *CMD_Control_Update_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_Update_S) ProtoMessage()               {}
func (*CMD_Control_Update_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CMD_Control_Update_S) GetRealUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.RealUserChip
	}
	return nil
}

func (m *CMD_Control_Update_S) GetDstUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.DstUserChip
	}
	return nil
}

type CMD_ChipSucc_S struct {
	ContinueChip     *bool   `protobuf:"varint,1,opt,name=continue_chip,json=continueChip" json:"continue_chip,omitempty"`
	ChipIndex        *uint32 `protobuf:"varint,2,opt,name=chip_index,json=chipIndex" json:"chip_index,omitempty"`
	ChipValue        *int64  `protobuf:"varint,3,opt,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	ShowScore        *int64  `protobuf:"varint,4,opt,name=show_score,json=showScore" json:"show_score,omitempty"`
	AndroidCheat     *bool   `protobuf:"varint,5,opt,name=android_cheat,json=androidCheat" json:"android_cheat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_ChipSucc_S) Reset()                    { *m = CMD_ChipSucc_S{} }
func (m *CMD_ChipSucc_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_ChipSucc_S) ProtoMessage()               {}
func (*CMD_ChipSucc_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CMD_ChipSucc_S) GetContinueChip() bool {
	if m != nil && m.ContinueChip != nil {
		return *m.ContinueChip
	}
	return false
}

func (m *CMD_ChipSucc_S) GetChipIndex() uint32 {
	if m != nil && m.ChipIndex != nil {
		return *m.ChipIndex
	}
	return 0
}

func (m *CMD_ChipSucc_S) GetChipValue() int64 {
	if m != nil && m.ChipValue != nil {
		return *m.ChipValue
	}
	return 0
}

func (m *CMD_ChipSucc_S) GetShowScore() int64 {
	if m != nil && m.ShowScore != nil {
		return *m.ShowScore
	}
	return 0
}

func (m *CMD_ChipSucc_S) GetAndroidCheat() bool {
	if m != nil && m.AndroidCheat != nil {
		return *m.AndroidCheat
	}
	return false
}

// 游戏的结算信息
type CMD_ClearUserChip_S struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	ChipValue        *int64  `protobuf:"varint,2,opt,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_ClearUserChip_S) Reset()                    { *m = CMD_ClearUserChip_S{} }
func (m *CMD_ClearUserChip_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_ClearUserChip_S) ProtoMessage()               {}
func (*CMD_ClearUserChip_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CMD_ClearUserChip_S) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *CMD_ClearUserChip_S) GetChipValue() int64 {
	if m != nil && m.ChipValue != nil {
		return *m.ChipValue
	}
	return 0
}

type CMD_ContinueChipResult_S struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_ContinueChipResult_S) Reset()                    { *m = CMD_ContinueChipResult_S{} }
func (m *CMD_ContinueChipResult_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_ContinueChipResult_S) ProtoMessage()               {}
func (*CMD_ContinueChipResult_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CMD_ContinueChipResult_S) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 游戏的结算信息
type CMD_SelfResult_S struct {
	WinScoreChange   *int64 `protobuf:"varint,1,opt,name=win_score_change,json=winScoreChange" json:"win_score_change,omitempty"`
	ChipValue        *int64 `protobuf:"varint,2,opt,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	NewScore         *int64 `protobuf:"varint,3,opt,name=new_score,json=newScore" json:"new_score,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_SelfResult_S) Reset()                    { *m = CMD_SelfResult_S{} }
func (m *CMD_SelfResult_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_SelfResult_S) ProtoMessage()               {}
func (*CMD_SelfResult_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CMD_SelfResult_S) GetWinScoreChange() int64 {
	if m != nil && m.WinScoreChange != nil {
		return *m.WinScoreChange
	}
	return 0
}

func (m *CMD_SelfResult_S) GetChipValue() int64 {
	if m != nil && m.ChipValue != nil {
		return *m.ChipValue
	}
	return 0
}

func (m *CMD_SelfResult_S) GetNewScore() int64 {
	if m != nil && m.NewScore != nil {
		return *m.NewScore
	}
	return 0
}

type CMD_UpdateSelfScore_S struct {
	SelfScoreShow    *int64 `protobuf:"varint,1,opt,name=self_score_show,json=selfScoreShow" json:"self_score_show,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_UpdateSelfScore_S) Reset()                    { *m = CMD_UpdateSelfScore_S{} }
func (m *CMD_UpdateSelfScore_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_UpdateSelfScore_S) ProtoMessage()               {}
func (*CMD_UpdateSelfScore_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CMD_UpdateSelfScore_S) GetSelfScoreShow() int64 {
	if m != nil && m.SelfScoreShow != nil {
		return *m.SelfScoreShow
	}
	return 0
}

type CMD_Control_UserInfo_S struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GameId           *uint32 `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	NickName         []byte  `protobuf:"bytes,3,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Score            *int64  `protobuf:"varint,4,opt,name=score" json:"score,omitempty"`
	KillProbability  *int32  `protobuf:"varint,5,opt,name=kill_probability,json=killProbability" json:"kill_probability,omitempty"`
	VipLev           *uint32 `protobuf:"varint,6,opt,name=vip_lev,json=vipLev" json:"vip_lev,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Control_UserInfo_S) Reset()                    { *m = CMD_Control_UserInfo_S{} }
func (m *CMD_Control_UserInfo_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_UserInfo_S) ProtoMessage()               {}
func (*CMD_Control_UserInfo_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *CMD_Control_UserInfo_S) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CMD_Control_UserInfo_S) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *CMD_Control_UserInfo_S) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *CMD_Control_UserInfo_S) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *CMD_Control_UserInfo_S) GetKillProbability() int32 {
	if m != nil && m.KillProbability != nil {
		return *m.KillProbability
	}
	return 0
}

func (m *CMD_Control_UserInfo_S) GetVipLev() uint32 {
	if m != nil && m.VipLev != nil {
		return *m.VipLev
	}
	return 0
}

type CMD_Control_StockInfo_S struct {
	StockScore       *int64  `protobuf:"varint,1,opt,name=stock_score,json=stockScore" json:"stock_score,omitempty"`
	DownLine         *int64  `protobuf:"varint,2,opt,name=down_line,json=downLine" json:"down_line,omitempty"`
	PutMoneyMax      *int64  `protobuf:"varint,3,opt,name=put_money_max,json=putMoneyMax" json:"put_money_max,omitempty"`
	PerRevenue       *uint32 `protobuf:"varint,4,opt,name=per_revenue,json=perRevenue" json:"per_revenue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Control_StockInfo_S) Reset()                    { *m = CMD_Control_StockInfo_S{} }
func (m *CMD_Control_StockInfo_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_StockInfo_S) ProtoMessage()               {}
func (*CMD_Control_StockInfo_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *CMD_Control_StockInfo_S) GetStockScore() int64 {
	if m != nil && m.StockScore != nil {
		return *m.StockScore
	}
	return 0
}

func (m *CMD_Control_StockInfo_S) GetDownLine() int64 {
	if m != nil && m.DownLine != nil {
		return *m.DownLine
	}
	return 0
}

func (m *CMD_Control_StockInfo_S) GetPutMoneyMax() int64 {
	if m != nil && m.PutMoneyMax != nil {
		return *m.PutMoneyMax
	}
	return 0
}

func (m *CMD_Control_StockInfo_S) GetPerRevenue() uint32 {
	if m != nil && m.PerRevenue != nil {
		return *m.PerRevenue
	}
	return 0
}

type CMD_Control_UserChip_S struct {
	UserId           *uint32          `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserChip         *CMD_UserChip_ST `protobuf:"bytes,2,opt,name=user_chip,json=userChip" json:"user_chip,omitempty"`
	Score            *int64           `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
	Insure           *int64           `protobuf:"varint,4,opt,name=insure" json:"insure,omitempty"`
	RedNameUserDown  []int64          `protobuf:"varint,5,rep,name=red_name_user_down,json=redNameUserDown" json:"red_name_user_down,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CMD_Control_UserChip_S) Reset()                    { *m = CMD_Control_UserChip_S{} }
func (m *CMD_Control_UserChip_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_UserChip_S) ProtoMessage()               {}
func (*CMD_Control_UserChip_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *CMD_Control_UserChip_S) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CMD_Control_UserChip_S) GetUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.UserChip
	}
	return nil
}

func (m *CMD_Control_UserChip_S) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *CMD_Control_UserChip_S) GetInsure() int64 {
	if m != nil && m.Insure != nil {
		return *m.Insure
	}
	return 0
}

func (m *CMD_Control_UserChip_S) GetRedNameUserDown() []int64 {
	if m != nil {
		return m.RedNameUserDown
	}
	return nil
}

type CMD_UserChipNotify_S struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ChipIndex        *uint32 `protobuf:"varint,2,opt,name=chip_index,json=chipIndex" json:"chip_index,omitempty"`
	ChipValue        *int64  `protobuf:"varint,3,opt,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_UserChipNotify_S) Reset()                    { *m = CMD_UserChipNotify_S{} }
func (m *CMD_UserChipNotify_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_UserChipNotify_S) ProtoMessage()               {}
func (*CMD_UserChipNotify_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CMD_UserChipNotify_S) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CMD_UserChipNotify_S) GetChipIndex() uint32 {
	if m != nil && m.ChipIndex != nil {
		return *m.ChipIndex
	}
	return 0
}

func (m *CMD_UserChipNotify_S) GetChipValue() int64 {
	if m != nil && m.ChipValue != nil {
		return *m.ChipValue
	}
	return 0
}

type CMD_UserContinue_ChipNotify_S struct {
	UserId            *uint32          `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ContinueChipIndex *CMD_UserChip_ST `protobuf:"bytes,2,opt,name=continue_chip_index,json=continueChipIndex" json:"continue_chip_index,omitempty"`
	XXX_unrecognized  []byte           `json:"-"`
}

func (m *CMD_UserContinue_ChipNotify_S) Reset()                    { *m = CMD_UserContinue_ChipNotify_S{} }
func (m *CMD_UserContinue_ChipNotify_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_UserContinue_ChipNotify_S) ProtoMessage()               {}
func (*CMD_UserContinue_ChipNotify_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CMD_UserContinue_ChipNotify_S) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CMD_UserContinue_ChipNotify_S) GetContinueChipIndex() *CMD_UserChip_ST {
	if m != nil {
		return m.ContinueChipIndex
	}
	return nil
}

type CMD_ReqBanker_Result struct {
	Result           []byte `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_ReqBanker_Result) Reset()                    { *m = CMD_ReqBanker_Result{} }
func (m *CMD_ReqBanker_Result) String() string            { return proto.CompactTextString(m) }
func (*CMD_ReqBanker_Result) ProtoMessage()               {}
func (*CMD_ReqBanker_Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *CMD_ReqBanker_Result) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type CMD_WaitBankerUserInfo struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName         []byte  `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	FaceId           *uint32 `protobuf:"varint,3,opt,name=face_id,json=faceId" json:"face_id,omitempty"`
	UserScore        *int64  `protobuf:"varint,4,opt,name=user_score,json=userScore" json:"user_score,omitempty"`
	FaceUrl          []byte  `protobuf:"bytes,5,opt,name=face_url,json=faceUrl" json:"face_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_WaitBankerUserInfo) Reset()                    { *m = CMD_WaitBankerUserInfo{} }
func (m *CMD_WaitBankerUserInfo) String() string            { return proto.CompactTextString(m) }
func (*CMD_WaitBankerUserInfo) ProtoMessage()               {}
func (*CMD_WaitBankerUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *CMD_WaitBankerUserInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CMD_WaitBankerUserInfo) GetUserName() []byte {
	if m != nil {
		return m.UserName
	}
	return nil
}

func (m *CMD_WaitBankerUserInfo) GetFaceId() uint32 {
	if m != nil && m.FaceId != nil {
		return *m.FaceId
	}
	return 0
}

func (m *CMD_WaitBankerUserInfo) GetUserScore() int64 {
	if m != nil && m.UserScore != nil {
		return *m.UserScore
	}
	return 0
}

func (m *CMD_WaitBankerUserInfo) GetFaceUrl() []byte {
	if m != nil {
		return m.FaceUrl
	}
	return nil
}

type CMD_BankerUserInfo struct {
	BankerUserId     *uint32                   `protobuf:"varint,1,opt,name=banker_user_id,json=bankerUserId" json:"banker_user_id,omitempty"`
	BankerName       []byte                    `protobuf:"bytes,2,opt,name=banker_name,json=bankerName" json:"banker_name,omitempty"`
	SitGameNum       *uint32                   `protobuf:"varint,3,opt,name=sit_game_num,json=sitGameNum" json:"sit_game_num,omitempty"`
	BankerScore      *int64                    `protobuf:"varint,4,opt,name=banker_score,json=bankerScore" json:"banker_score,omitempty"`
	SelfSlot         *uint32                   `protobuf:"varint,5,opt,name=self_slot,json=selfSlot" json:"self_slot,omitempty"`
	ReqUserCount     *uint32                   `protobuf:"varint,6,opt,name=req_user_count,json=reqUserCount" json:"req_user_count,omitempty"`
	ReqArrUserInfo   []*CMD_WaitBankerUserInfo `protobuf:"bytes,7,rep,name=req_arr_user_info,json=reqArrUserInfo" json:"req_arr_user_info,omitempty"`
	FaceId           *uint32                   `protobuf:"varint,8,opt,name=face_id,json=faceId" json:"face_id,omitempty"`
	FaceUrl          []byte                    `protobuf:"bytes,9,opt,name=face_url,json=faceUrl" json:"face_url,omitempty"`
	FrobUser         *bool                     `protobuf:"varint,10,opt,name=frob_user,json=frobUser" json:"frob_user,omitempty"`
	Monetaryt        *int32                    `protobuf:"varint,11,opt,name=monetaryt" json:"monetaryt,omitempty"`
	Monetaryv        *int64                    `protobuf:"varint,12,opt,name=monetaryv" json:"monetaryv,omitempty"`
	UserId           *uint32                   `protobuf:"varint,13,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	IrobAct          *bool                     `protobuf:"varint,14,opt,name=irob_act,json=irobAct" json:"irob_act,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *CMD_BankerUserInfo) Reset()                    { *m = CMD_BankerUserInfo{} }
func (m *CMD_BankerUserInfo) String() string            { return proto.CompactTextString(m) }
func (*CMD_BankerUserInfo) ProtoMessage()               {}
func (*CMD_BankerUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *CMD_BankerUserInfo) GetBankerUserId() uint32 {
	if m != nil && m.BankerUserId != nil {
		return *m.BankerUserId
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetBankerName() []byte {
	if m != nil {
		return m.BankerName
	}
	return nil
}

func (m *CMD_BankerUserInfo) GetSitGameNum() uint32 {
	if m != nil && m.SitGameNum != nil {
		return *m.SitGameNum
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetBankerScore() int64 {
	if m != nil && m.BankerScore != nil {
		return *m.BankerScore
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetSelfSlot() uint32 {
	if m != nil && m.SelfSlot != nil {
		return *m.SelfSlot
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetReqUserCount() uint32 {
	if m != nil && m.ReqUserCount != nil {
		return *m.ReqUserCount
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetReqArrUserInfo() []*CMD_WaitBankerUserInfo {
	if m != nil {
		return m.ReqArrUserInfo
	}
	return nil
}

func (m *CMD_BankerUserInfo) GetFaceId() uint32 {
	if m != nil && m.FaceId != nil {
		return *m.FaceId
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetFaceUrl() []byte {
	if m != nil {
		return m.FaceUrl
	}
	return nil
}

func (m *CMD_BankerUserInfo) GetFrobUser() bool {
	if m != nil && m.FrobUser != nil {
		return *m.FrobUser
	}
	return false
}

func (m *CMD_BankerUserInfo) GetMonetaryt() int32 {
	if m != nil && m.Monetaryt != nil {
		return *m.Monetaryt
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetMonetaryv() int64 {
	if m != nil && m.Monetaryv != nil {
		return *m.Monetaryv
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *CMD_BankerUserInfo) GetIrobAct() bool {
	if m != nil && m.IrobAct != nil {
		return *m.IrobAct
	}
	return false
}

type CMD_BankerResult_S struct {
	BankerUserId     *uint32  `protobuf:"varint,1,opt,name=banker_user_id,json=bankerUserId" json:"banker_user_id,omitempty"`
	BankerName       []byte   `protobuf:"bytes,2,opt,name=banker_name,json=bankerName" json:"banker_name,omitempty"`
	BankerWin        *int64   `protobuf:"varint,3,opt,name=banker_win,json=bankerWin" json:"banker_win,omitempty"`
	UserCount        *uint32  `protobuf:"varint,4,opt,name=user_count,json=userCount" json:"user_count,omitempty"`
	NickName         [][]byte `protobuf:"bytes,5,rep,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	UserWin          []int64  `protobuf:"varint,6,rep,name=user_win,json=userWin" json:"user_win,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMD_BankerResult_S) Reset()                    { *m = CMD_BankerResult_S{} }
func (m *CMD_BankerResult_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_BankerResult_S) ProtoMessage()               {}
func (*CMD_BankerResult_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *CMD_BankerResult_S) GetBankerUserId() uint32 {
	if m != nil && m.BankerUserId != nil {
		return *m.BankerUserId
	}
	return 0
}

func (m *CMD_BankerResult_S) GetBankerName() []byte {
	if m != nil {
		return m.BankerName
	}
	return nil
}

func (m *CMD_BankerResult_S) GetBankerWin() int64 {
	if m != nil && m.BankerWin != nil {
		return *m.BankerWin
	}
	return 0
}

func (m *CMD_BankerResult_S) GetUserCount() uint32 {
	if m != nil && m.UserCount != nil {
		return *m.UserCount
	}
	return 0
}

func (m *CMD_BankerResult_S) GetNickName() [][]byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *CMD_BankerResult_S) GetUserWin() []int64 {
	if m != nil {
		return m.UserWin
	}
	return nil
}

type CMD_EMPTY_MESSAGE_S struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_EMPTY_MESSAGE_S) Reset()                    { *m = CMD_EMPTY_MESSAGE_S{} }
func (m *CMD_EMPTY_MESSAGE_S) String() string            { return proto.CompactTextString(m) }
func (*CMD_EMPTY_MESSAGE_S) ProtoMessage()               {}
func (*CMD_EMPTY_MESSAGE_S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type CMD_Control_SelectDst_C struct {
	UserId           *uint32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Control_SelectDst_C) Reset()                    { *m = CMD_Control_SelectDst_C{} }
func (m *CMD_Control_SelectDst_C) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_SelectDst_C) ProtoMessage()               {}
func (*CMD_Control_SelectDst_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *CMD_Control_SelectDst_C) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type CMD_UserChip_C struct {
	ChipIndex        *uint32 `protobuf:"varint,1,opt,name=chip_index,json=chipIndex" json:"chip_index,omitempty"`
	ChipValue        *int64  `protobuf:"varint,2,opt,name=chip_value,json=chipValue" json:"chip_value,omitempty"`
	AndroidCheat     *bool   `protobuf:"varint,3,opt,name=android_cheat,json=androidCheat" json:"android_cheat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_UserChip_C) Reset()                    { *m = CMD_UserChip_C{} }
func (m *CMD_UserChip_C) String() string            { return proto.CompactTextString(m) }
func (*CMD_UserChip_C) ProtoMessage()               {}
func (*CMD_UserChip_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *CMD_UserChip_C) GetChipIndex() uint32 {
	if m != nil && m.ChipIndex != nil {
		return *m.ChipIndex
	}
	return 0
}

func (m *CMD_UserChip_C) GetChipValue() int64 {
	if m != nil && m.ChipValue != nil {
		return *m.ChipValue
	}
	return 0
}

func (m *CMD_UserChip_C) GetAndroidCheat() bool {
	if m != nil && m.AndroidCheat != nil {
		return *m.AndroidCheat
	}
	return false
}

type CMD_UserContinueChip_C struct {
	StUserChip       *CMD_UserChip_ST `protobuf:"bytes,1,opt,name=st_user_chip,json=stUserChip" json:"st_user_chip,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CMD_UserContinueChip_C) Reset()                    { *m = CMD_UserContinueChip_C{} }
func (m *CMD_UserContinueChip_C) String() string            { return proto.CompactTextString(m) }
func (*CMD_UserContinueChip_C) ProtoMessage()               {}
func (*CMD_UserContinueChip_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *CMD_UserContinueChip_C) GetStUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.StUserChip
	}
	return nil
}

type CMD_Control_SetDst_C struct {
	Control          *bool   `protobuf:"varint,1,opt,name=control" json:"control,omitempty"`
	DstIndex         *uint32 `protobuf:"varint,2,opt,name=dst_index,json=dstIndex" json:"dst_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_Control_SetDst_C) Reset()                    { *m = CMD_Control_SetDst_C{} }
func (m *CMD_Control_SetDst_C) String() string            { return proto.CompactTextString(m) }
func (*CMD_Control_SetDst_C) ProtoMessage()               {}
func (*CMD_Control_SetDst_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *CMD_Control_SetDst_C) GetControl() bool {
	if m != nil && m.Control != nil {
		return *m.Control
	}
	return false
}

func (m *CMD_Control_SetDst_C) GetDstIndex() uint32 {
	if m != nil && m.DstIndex != nil {
		return *m.DstIndex
	}
	return 0
}

type CMD_ReqBanker_C struct {
	Request          *bool  `protobuf:"varint,1,opt,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_ReqBanker_C) Reset()                    { *m = CMD_ReqBanker_C{} }
func (m *CMD_ReqBanker_C) String() string            { return proto.CompactTextString(m) }
func (*CMD_ReqBanker_C) ProtoMessage()               {}
func (*CMD_ReqBanker_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *CMD_ReqBanker_C) GetRequest() bool {
	if m != nil && m.Request != nil {
		return *m.Request
	}
	return false
}

type CMD_Control_UserTotalChipInfo_S struct {
	RealUserChip     *CMD_UserChip_ST `protobuf:"bytes,1,opt,name=real_user_chip,json=realUserChip" json:"real_user_chip,omitempty"`
	AiUserChip       *CMD_UserChip_ST `protobuf:"bytes,2,opt,name=ai_user_chip,json=aiUserChip" json:"ai_user_chip,omitempty"`
	ForWinUserChip   *CMD_UserChip_ST `protobuf:"bytes,3,opt,name=for_win_user_chip,json=forWinUserChip" json:"for_win_user_chip,omitempty"`
	ForLostUserChip  *CMD_UserChip_ST `protobuf:"bytes,4,opt,name=for_lost_user_chip,json=forLostUserChip" json:"for_lost_user_chip,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *CMD_Control_UserTotalChipInfo_S) Reset()         { *m = CMD_Control_UserTotalChipInfo_S{} }
func (m *CMD_Control_UserTotalChipInfo_S) String() string { return proto.CompactTextString(m) }
func (*CMD_Control_UserTotalChipInfo_S) ProtoMessage()    {}
func (*CMD_Control_UserTotalChipInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{35}
}

func (m *CMD_Control_UserTotalChipInfo_S) GetRealUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.RealUserChip
	}
	return nil
}

func (m *CMD_Control_UserTotalChipInfo_S) GetAiUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.AiUserChip
	}
	return nil
}

func (m *CMD_Control_UserTotalChipInfo_S) GetForWinUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.ForWinUserChip
	}
	return nil
}

func (m *CMD_Control_UserTotalChipInfo_S) GetForLostUserChip() *CMD_UserChip_ST {
	if m != nil {
		return m.ForLostUserChip
	}
	return nil
}

type CMD_SUB_C_ONLINE_TOTAL struct {
	ServerKind       *uint32 `protobuf:"varint,1,opt,name=server_kind,json=serverKind" json:"server_kind,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_SUB_C_ONLINE_TOTAL) Reset()                    { *m = CMD_SUB_C_ONLINE_TOTAL{} }
func (m *CMD_SUB_C_ONLINE_TOTAL) String() string            { return proto.CompactTextString(m) }
func (*CMD_SUB_C_ONLINE_TOTAL) ProtoMessage()               {}
func (*CMD_SUB_C_ONLINE_TOTAL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *CMD_SUB_C_ONLINE_TOTAL) GetServerKind() uint32 {
	if m != nil && m.ServerKind != nil {
		return *m.ServerKind
	}
	return 0
}

type CMD_SUB_S_ONLINE_TOTAL struct {
	ServerKind       *uint32 `protobuf:"varint,1,opt,name=server_kind,json=serverKind" json:"server_kind,omitempty"`
	OnlineTotal      *uint32 `protobuf:"varint,2,opt,name=online_total,json=onlineTotal" json:"online_total,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_SUB_S_ONLINE_TOTAL) Reset()                    { *m = CMD_SUB_S_ONLINE_TOTAL{} }
func (m *CMD_SUB_S_ONLINE_TOTAL) String() string            { return proto.CompactTextString(m) }
func (*CMD_SUB_S_ONLINE_TOTAL) ProtoMessage()               {}
func (*CMD_SUB_S_ONLINE_TOTAL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *CMD_SUB_S_ONLINE_TOTAL) GetServerKind() uint32 {
	if m != nil && m.ServerKind != nil {
		return *m.ServerKind
	}
	return 0
}

func (m *CMD_SUB_S_ONLINE_TOTAL) GetOnlineTotal() uint32 {
	if m != nil && m.OnlineTotal != nil {
		return *m.OnlineTotal
	}
	return 0
}

type CMD_SUB_C_ROBBANK struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMD_SUB_C_ROBBANK) Reset()                    { *m = CMD_SUB_C_ROBBANK{} }
func (m *CMD_SUB_C_ROBBANK) String() string            { return proto.CompactTextString(m) }
func (*CMD_SUB_C_ROBBANK) ProtoMessage()               {}
func (*CMD_SUB_C_ROBBANK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type CMD_SUB_S_AndroidUpdateChip struct {
	CheatMode        *bool   `protobuf:"varint,1,opt,name=cheat_mode,json=cheatMode" json:"cheat_mode,omitempty"`
	ChipIndex        *uint32 `protobuf:"varint,2,opt,name=chip_index,json=chipIndex" json:"chip_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMD_SUB_S_AndroidUpdateChip) Reset()                    { *m = CMD_SUB_S_AndroidUpdateChip{} }
func (m *CMD_SUB_S_AndroidUpdateChip) String() string            { return proto.CompactTextString(m) }
func (*CMD_SUB_S_AndroidUpdateChip) ProtoMessage()               {}
func (*CMD_SUB_S_AndroidUpdateChip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *CMD_SUB_S_AndroidUpdateChip) GetCheatMode() bool {
	if m != nil && m.CheatMode != nil {
		return *m.CheatMode
	}
	return false
}

func (m *CMD_SUB_S_AndroidUpdateChip) GetChipIndex() uint32 {
	if m != nil && m.ChipIndex != nil {
		return *m.ChipIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*CMD_SUB_C_REQ_BANKER)(nil), "CMD.CMD_SUB_C_REQ_BANKER")
	proto.RegisterType((*CMD_SUB_S_REQ_BANKER)(nil), "CMD.CMD_SUB_S_REQ_BANKER")
	proto.RegisterType((*CMD_Userinfo_S)(nil), "CMD.CMD_Userinfo_S")
	proto.RegisterType((*CMD_UserChip_ST)(nil), "CMD.CMD_UserChip_ST")
	proto.RegisterType((*CMD_Sence_Free)(nil), "CMD.CMD_Sence_Free")
	proto.RegisterType((*CMD_GameStart_S)(nil), "CMD.CMD_GameStart_S")
	proto.RegisterType((*CMD_GameEnd_Info_S)(nil), "CMD.CMD_GameEnd_Info_S")
	proto.RegisterType((*CMD_UpdataChip_S)(nil), "CMD.CMD_UpdataChip_S")
	proto.RegisterType((*CMD_SysMessage_S)(nil), "CMD.CMD_SysMessage_S")
	proto.RegisterType((*CMD_Gameinfo_S)(nil), "CMD.CMD_Gameinfo_S")
	proto.RegisterType((*CMD_GameOpenLog_S)(nil), "CMD.CMD_GameOpenLog_S")
	proto.RegisterType((*CMD_Control_UserLeave_S)(nil), "CMD.CMD_Control_UserLeave_S")
	proto.RegisterType((*CMD_Control_DealRet_S)(nil), "CMD.CMD_Control_DealRet_S")
	proto.RegisterType((*CMD_GameResultinfo_S)(nil), "CMD.CMD_GameResultinfo_S")
	proto.RegisterType((*CMD_Control_Update_S)(nil), "CMD.CMD_Control_Update_S")
	proto.RegisterType((*CMD_ChipSucc_S)(nil), "CMD.CMD_ChipSucc_S")
	proto.RegisterType((*CMD_ClearUserChip_S)(nil), "CMD.CMD_ClearUserChip_S")
	proto.RegisterType((*CMD_ContinueChipResult_S)(nil), "CMD.CMD_ContinueChipResult_S")
	proto.RegisterType((*CMD_SelfResult_S)(nil), "CMD.CMD_SelfResult_S")
	proto.RegisterType((*CMD_UpdateSelfScore_S)(nil), "CMD.CMD_UpdateSelfScore_S")
	proto.RegisterType((*CMD_Control_UserInfo_S)(nil), "CMD.CMD_Control_UserInfo_S")
	proto.RegisterType((*CMD_Control_StockInfo_S)(nil), "CMD.CMD_Control_StockInfo_S")
	proto.RegisterType((*CMD_Control_UserChip_S)(nil), "CMD.CMD_Control_UserChip_S")
	proto.RegisterType((*CMD_UserChipNotify_S)(nil), "CMD.CMD_UserChipNotify_S")
	proto.RegisterType((*CMD_UserContinue_ChipNotify_S)(nil), "CMD.CMD_UserContinue_ChipNotify_S")
	proto.RegisterType((*CMD_ReqBanker_Result)(nil), "CMD.CMD_ReqBanker_Result")
	proto.RegisterType((*CMD_WaitBankerUserInfo)(nil), "CMD.CMD_WaitBankerUserInfo")
	proto.RegisterType((*CMD_BankerUserInfo)(nil), "CMD.CMD_BankerUserInfo")
	proto.RegisterType((*CMD_BankerResult_S)(nil), "CMD.CMD_BankerResult_S")
	proto.RegisterType((*CMD_EMPTY_MESSAGE_S)(nil), "CMD.CMD_EMPTY_MESSAGE_S")
	proto.RegisterType((*CMD_Control_SelectDst_C)(nil), "CMD.CMD_Control_SelectDst_C")
	proto.RegisterType((*CMD_UserChip_C)(nil), "CMD.CMD_UserChip_C")
	proto.RegisterType((*CMD_UserContinueChip_C)(nil), "CMD.CMD_UserContinueChip_C")
	proto.RegisterType((*CMD_Control_SetDst_C)(nil), "CMD.CMD_Control_SetDst_C")
	proto.RegisterType((*CMD_ReqBanker_C)(nil), "CMD.CMD_ReqBanker_C")
	proto.RegisterType((*CMD_Control_UserTotalChipInfo_S)(nil), "CMD.CMD_Control_UserTotalChipInfo_S")
	proto.RegisterType((*CMD_SUB_C_ONLINE_TOTAL)(nil), "CMD.CMD_SUB_C_ONLINE_TOTAL")
	proto.RegisterType((*CMD_SUB_S_ONLINE_TOTAL)(nil), "CMD.CMD_SUB_S_ONLINE_TOTAL")
	proto.RegisterType((*CMD_SUB_C_ROBBANK)(nil), "CMD.CMD_SUB_C_ROBBANK")
	proto.RegisterType((*CMD_SUB_S_AndroidUpdateChip)(nil), "CMD.CMD_SUB_S_AndroidUpdateChip")
}

func init() { proto.RegisterFile("CMD_FQZS_Game.CMD", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xdd, 0x6e, 0x1b, 0xb9,
	0x15, 0x86, 0x3c, 0x8e, 0x2d, 0x1d, 0x49, 0x76, 0x32, 0xc9, 0x26, 0x0a, 0xd2, 0x20, 0xee, 0x6c,
	0x51, 0xb8, 0x58, 0xc0, 0xe8, 0xe6, 0x62, 0xd1, 0x16, 0x45, 0x17, 0xb6, 0xec, 0x64, 0x8d, 0x48,
	0x4e, 0x76, 0xc6, 0x6e, 0xd0, 0x1f, 0x80, 0x60, 0x34, 0x94, 0x4d, 0x78, 0x44, 0x8e, 0x49, 0x8e,
	0x1c, 0x01, 0x6d, 0x6f, 0x7a, 0xdb, 0x17, 0x28, 0xd0, 0x9b, 0x3e, 0x45, 0xaf, 0x8a, 0xa2, 0x6f,
	0xd0, 0xbe, 0x47, 0x1f, 0xa2, 0x38, 0x24, 0x67, 0x34, 0x52, 0x62, 0xad, 0x8b, 0x2d, 0xda, 0x3b,
	0xf1, 0x0c, 0xc9, 0x73, 0x78, 0xbe, 0xc3, 0xef, 0x7c, 0x14, 0xdc, 0xef, 0x0f, 0x0f, 0xc9, 0x8b,
	0xaf, 0x7f, 0x99, 0x90, 0x97, 0x74, 0xc2, 0xf6, 0x72, 0x25, 0x8d, 0x0c, 0x83, 0xfe, 0xf0, 0x30,
	0xfa, 0x1c, 0x1e, 0xe0, 0xb7, 0xe4, 0xec, 0x80, 0xf4, 0x49, 0x7c, 0xf4, 0x35, 0x39, 0xd8, 0x3f,
	0x79, 0x75, 0x14, 0x87, 0x8f, 0xa1, 0xa9, 0xd8, 0x15, 0x31, 0xb3, 0x9c, 0xf5, 0x1a, 0x3b, 0x8d,
	0xdd, 0x3b, 0xf1, 0xa6, 0x62, 0x57, 0xa7, 0xb3, 0x9c, 0x45, 0x3f, 0x9b, 0x2f, 0x49, 0xea, 0x4b,
	0xbe, 0x0f, 0xdb, 0xb8, 0x44, 0x31, 0x5d, 0x64, 0x86, 0x70, 0x31, 0x96, 0x76, 0x65, 0x27, 0xee,
	0x2a, 0x76, 0x15, 0x5b, 0xeb, 0xb1, 0x18, 0xcb, 0xe8, 0xef, 0x0d, 0xd8, 0xc2, 0x0d, 0xce, 0x34,
	0x53, 0x38, 0x8b, 0x24, 0xe1, 0x53, 0x80, 0x42, 0x33, 0x45, 0xf4, 0x48, 0x2a, 0xe7, 0x2f, 0x88,
	0x5b, 0x68, 0x49, 0xd0, 0x10, 0x3e, 0x81, 0x96, 0xe0, 0xa3, 0x4b, 0x22, 0xe8, 0x84, 0xf5, 0xd6,
	0xec, 0x9e, 0x4d, 0x34, 0x9c, 0xd0, 0x09, 0xc3, 0xb5, 0xa3, 0x0b, 0x9e, 0x93, 0x29, 0xcd, 0x0a,
	0xd6, 0x0b, 0x76, 0x82, 0xdd, 0x6e, 0xdc, 0x42, 0xcb, 0xcf, 0xd1, 0x10, 0xfe, 0x10, 0x1e, 0xbc,
	0xa3, 0xe2, 0xb2, 0xdc, 0x9c, 0x28, 0x76, 0x55, 0x30, 0x6d, 0x7a, 0xeb, 0xd6, 0x49, 0xe8, 0xbe,
	0x59, 0x37, 0xb1, 0xfb, 0x12, 0x46, 0xd0, 0xb5, 0x1b, 0x16, 0x39, 0xc9, 0xf8, 0x84, 0x9b, 0xde,
	0x1d, 0x7b, 0xfe, 0x36, 0x1a, 0xcf, 0xf2, 0x01, 0x9a, 0xa2, 0x3d, 0xd8, 0x2e, 0x8f, 0xd0, 0xc7,
	0xb9, 0xc9, 0x29, 0x06, 0x69, 0xcf, 0x80, 0xd3, 0x7a, 0x8d, 0x9d, 0x60, 0x37, 0x88, 0x9b, 0x85,
	0xff, 0x1e, 0xfd, 0xd5, 0x9f, 0x39, 0x61, 0x62, 0xc4, 0xc8, 0x0b, 0xc5, 0x58, 0xf8, 0x0c, 0xda,
	0xe7, 0x74, 0xc2, 0x88, 0x36, 0xd4, 0x14, 0xda, 0x1e, 0xba, 0x1b, 0x03, 0x9a, 0x12, 0x6b, 0x59,
	0x4a, 0xca, 0xda, 0x72, 0x52, 0x3e, 0xaf, 0xfb, 0x0b, 0x76, 0x1a, 0xbb, 0xed, 0xe7, 0x0f, 0xf6,
	0xfa, 0xc3, 0xc3, 0xbd, 0xa5, 0xc0, 0xe6, 0x51, 0x84, 0x3f, 0x82, 0x2e, 0xcd, 0x32, 0x32, 0x5f,
	0xb6, 0xbe, 0x62, 0x59, 0x9b, 0x66, 0x59, 0x39, 0x8e, 0x7e, 0xeb, 0xce, 0xfb, 0xd2, 0x45, 0xa7,
	0x0c, 0x49, 0xb0, 0x42, 0x52, 0x6d, 0xe6, 0x15, 0xd2, 0x8d, 0x37, 0x53, 0x6d, 0xb0, 0x42, 0x30,
	0x15, 0xf8, 0x89, 0x8b, 0x94, 0xbd, 0xb7, 0x81, 0x77, 0x63, 0x9c, 0x7b, 0x8c, 0x63, 0x5c, 0x97,
	0x51, 0x6d, 0x48, 0x2e, 0xb5, 0x0d, 0xbb, 0x1b, 0x6f, 0xe2, 0xf8, 0x8d, 0xd4, 0xe1, 0x23, 0xc0,
	0x2d, 0xec, 0x97, 0x75, 0xfb, 0x65, 0x23, 0xb5, 0x1f, 0xa2, 0x7f, 0x34, 0x20, 0x2c, 0xfd, 0x1f,
	0x89, 0x94, 0x1c, 0xbb, 0xb2, 0xf9, 0x14, 0xba, 0x1e, 0x5b, 0x3c, 0x12, 0x4f, 0x7d, 0x1c, 0x1d,
	0x67, 0xb4, 0xf5, 0x95, 0x62, 0x9e, 0xfd, 0xa4, 0x5a, 0xf9, 0x80, 0x33, 0x95, 0x05, 0xe4, 0x27,
	0x5c, 0x73, 0x61, 0x43, 0x0a, 0xe2, 0x96, 0xb3, 0xbc, 0xe5, 0xa2, 0x82, 0x61, 0x24, 0x0b, 0x61,
	0x7c, 0x5c, 0x36, 0xf3, 0x7d, 0x34, 0x2c, 0xd6, 0xe6, 0x9d, 0x9d, 0x60, 0xa1, 0x36, 0x1f, 0x83,
	0x4d, 0xbe, 0xdd, 0x78, 0xc3, 0x96, 0xc4, 0x26, 0x8e, 0xdf, 0x72, 0x11, 0xfd, 0xbe, 0x01, 0x77,
	0x6d, 0xca, 0xf3, 0x94, 0x1a, 0xea, 0x92, 0xbe, 0x88, 0x69, 0xe3, 0x56, 0x98, 0xfe, 0x14, 0xb6,
	0x11, 0x53, 0xcd, 0xd4, 0xb4, 0x5c, 0xb8, 0xb6, 0x62, 0x21, 0x16, 0x40, 0x62, 0xe7, 0x5a, 0x5c,
	0x4f, 0x5c, 0x10, 0xc9, 0x4c, 0x0f, 0x99, 0xd6, 0xf4, 0x9c, 0x39, 0x60, 0xf5, 0x4c, 0x2f, 0x00,
	0xab, 0x67, 0xda, 0x02, 0xfb, 0x0c, 0xda, 0xf8, 0x69, 0xe2, 0xe6, 0x96, 0xb9, 0xd4, 0xd5, 0xea,
	0x68, 0xec, 0xca, 0x1c, 0x71, 0xf2, 0x57, 0x1b, 0xcb, 0x7c, 0x42, 0x3f, 0x28, 0xf3, 0x09, 0x2d,
	0xcb, 0xfc, 0x19, 0xb4, 0x0d, 0x9f, 0x30, 0xe5, 0x2f, 0xb0, 0x2b, 0x17, 0xb0, 0x26, 0x77, 0x83,
	0x43, 0x58, 0xcf, 0xa5, 0x48, 0x3d, 0x32, 0xf6, 0x77, 0x14, 0xc3, 0xbd, 0xd2, 0xcf, 0xeb, 0x9c,
	0x89, 0x81, 0x3c, 0x27, 0x09, 0x42, 0x41, 0x55, 0x09, 0x94, 0x73, 0xd4, 0xa4, 0xca, 0xe3, 0xb4,
	0x03, 0x1d, 0xfc, 0x28, 0x73, 0x26, 0x48, 0x26, 0xcf, 0x7b, 0x6b, 0x96, 0x28, 0x80, 0x2a, 0xe5,
	0x37, 0x88, 0x9e, 0xc3, 0x23, 0xdc, 0xb3, 0x2f, 0x85, 0x51, 0x32, 0xb3, 0x59, 0x1b, 0x30, 0x3a,
	0xc5, 0x94, 0x3c, 0x02, 0x8b, 0x1b, 0xa9, 0x4a, 0x6c, 0x03, 0x87, 0xc7, 0x69, 0xf4, 0x15, 0x7c,
	0x52, 0x5f, 0x73, 0xc8, 0x68, 0x16, 0x33, 0xbc, 0x1d, 0x77, 0x21, 0x50, 0xac, 0x8c, 0x02, 0x7f,
	0x62, 0x1d, 0x79, 0x6a, 0x4c, 0x99, 0xf6, 0xa9, 0x6b, 0x39, 0xcb, 0x21, 0xd3, 0xd1, 0x6f, 0x1c,
	0xab, 0xe2, 0x89, 0x1c, 0x57, 0xfa, 0xfc, 0xed, 0xc2, 0xdd, 0x6b, 0x2e, 0x3c, 0x79, 0x8d, 0x2e,
	0xa8, 0x38, 0x2f, 0x09, 0x72, 0xeb, 0x9a, 0x0b, 0x4b, 0x05, 0x7d, 0x6b, 0x5d, 0x22, 0x42, 0xcf,
	0x17, 0x73, 0x22, 0xc4, 0x42, 0x65, 0xd7, 0x9e, 0x4d, 0x5c, 0x2e, 0x9b, 0x82, 0x5d, 0xdb, 0x1d,
	0xa2, 0x3f, 0x34, 0x9c, 0xfb, 0xea, 0xf0, 0x58, 0x95, 0x78, 0xf2, 0x9f, 0xc0, 0x96, 0x62, 0xb4,
	0xce, 0x19, 0xab, 0xca, 0xb2, 0x83, 0x73, 0xcf, 0x6a, 0x74, 0x83, 0xd7, 0x79, 0xbe, 0x74, 0x55,
	0x61, 0xb6, 0x53, 0x6d, 0x2a, 0xba, 0xf9, 0x8b, 0xa7, 0x4b, 0x1c, 0x24, 0xc5, 0x68, 0xe4, 0xee,
	0xfa, 0x48, 0x0a, 0xc3, 0x45, 0xc1, 0xe6, 0x71, 0x34, 0xe3, 0x4e, 0x69, 0xb4, 0x1e, 0xcb, 0x14,
	0xd4, 0x99, 0xc7, 0xa6, 0xc0, 0x51, 0xcf, 0x72, 0xab, 0x58, 0xca, 0xd0, 0x53, 0x00, 0x7d, 0x21,
	0xcb, 0x14, 0xb9, 0x06, 0xd1, 0x42, 0x8b, 0x23, 0xdc, 0x4f, 0xa1, 0x4b, 0x45, 0xaa, 0x24, 0x4f,
	0xc9, 0xe8, 0x82, 0x51, 0xd7, 0x17, 0x9a, 0x71, 0xc7, 0x1b, 0xfb, 0x68, 0x8b, 0x06, 0xae, 0xd7,
	0xf6, 0x33, 0x46, 0xd5, 0xfc, 0x78, 0xe1, 0x43, 0xd8, 0x70, 0x50, 0x97, 0xf5, 0xe3, 0x46, 0xdf,
	0x80, 0x59, 0xf4, 0x1c, 0x7a, 0x25, 0x2a, 0xe5, 0x19, 0x5d, 0x71, 0xdc, 0xbc, 0x65, 0xf4, 0xde,
	0x5f, 0x69, 0x96, 0x8d, 0xab, 0xb9, 0xff, 0x9b, 0x22, 0xfa, 0xd2, 0x5d, 0x06, 0x57, 0x3b, 0xe8,
	0xdf, 0x9a, 0x49, 0x82, 0xca, 0x40, 0xb3, 0x6c, 0xec, 0xfd, 0x63, 0x46, 0xbd, 0xf7, 0xae, 0x2e,
	0x67, 0x25, 0x17, 0xf2, 0x1a, 0x95, 0xc1, 0xc3, 0xe5, 0x2b, 0xe8, 0xa9, 0xfe, 0xa6, 0x1b, 0x88,
	0x1f, 0x6c, 0x1b, 0xe5, 0xa9, 0xc7, 0x7b, 0x03, 0x87, 0xc7, 0xe9, 0x22, 0x31, 0x07, 0x4b, 0xa2,
	0xe1, 0x01, 0xdc, 0xa9, 0xa3, 0xec, 0x06, 0xe1, 0x0f, 0xe0, 0xee, 0x25, 0xcf, 0x32, 0x92, 0x2b,
	0xf9, 0x8e, 0xbe, 0xe3, 0x19, 0x37, 0x33, 0xdf, 0xfc, 0xb7, 0xd1, 0xfe, 0x66, 0x6e, 0x46, 0xb7,
	0x53, 0x9e, 0x93, 0x8c, 0x4d, 0x7b, 0x1b, 0xce, 0xed, 0x94, 0xe7, 0x03, 0x36, 0x8d, 0xfe, 0xd4,
	0x58, 0xa4, 0x91, 0xc4, 0xc8, 0xd1, 0xe5, 0x71, 0xc5, 0x85, 0x1a, 0x87, 0x0b, 0x3a, 0x07, 0xac,
	0xa9, 0x12, 0x3a, 0xa9, 0xbc, 0x16, 0x24, 0xe3, 0xa2, 0x4c, 0x7e, 0x13, 0x0d, 0x03, 0x2e, 0x18,
	0xea, 0x92, 0xbc, 0x30, 0x64, 0x22, 0x05, 0x9b, 0x91, 0x09, 0x7d, 0xef, 0xf3, 0xdf, 0xce, 0x0b,
	0x33, 0x44, 0xdb, 0x90, 0xbe, 0x47, 0x0f, 0x39, 0x53, 0x44, 0xb1, 0x29, 0x13, 0x05, 0xf3, 0xdd,
	0x0a, 0x72, 0xa6, 0x62, 0x67, 0x89, 0xfe, 0xf6, 0x91, 0x14, 0xfb, 0x1a, 0xbd, 0x31, 0xc5, 0x0b,
	0x5d, 0x69, 0xed, 0x56, 0x5d, 0xa9, 0xca, 0x6f, 0x50, 0xcf, 0xef, 0x43, 0xd8, 0xe0, 0x42, 0x17,
	0x55, 0xda, 0xfd, 0x28, 0xfc, 0x0c, 0x42, 0xc5, 0x52, 0x8b, 0x94, 0x63, 0x0b, 0x3c, 0xb3, 0x6d,
	0xa6, 0x41, 0xbc, 0xad, 0x58, 0x8a, 0x90, 0xa1, 0x9f, 0x43, 0x79, 0x2d, 0xa2, 0x89, 0x63, 0xaa,
	0xd2, 0xef, 0x89, 0x34, 0x7c, 0x3c, 0x5b, 0x15, 0xfe, 0xb7, 0x22, 0x85, 0xe8, 0x77, 0xf0, 0xb4,
	0x72, 0x57, 0xf2, 0xcf, 0xed, 0xfc, 0x1e, 0xc2, 0xfd, 0x05, 0xc6, 0xaa, 0x05, 0x70, 0x53, 0x02,
	0xef, 0xd5, 0xd9, 0xcc, 0x86, 0x17, 0xed, 0xb9, 0xe3, 0xc6, 0xec, 0xea, 0xc0, 0x89, 0x14, 0x77,
	0xa9, 0x97, 0xae, 0x7f, 0xa7, 0xba, 0xfe, 0x7f, 0xf6, 0x00, 0xbf, 0xa5, 0xdc, 0x1c, 0x54, 0x3a,
	0x08, 0x0b, 0xf0, 0xe6, 0x48, 0x4b, 0xe9, 0x5a, 0xd7, 0xd7, 0x68, 0xb0, 0x57, 0xe5, 0x11, 0x6c,
	0x8e, 0xe9, 0xc8, 0x5e, 0x30, 0x27, 0xd7, 0x36, 0x70, 0xe8, 0xf2, 0x5a, 0xd3, 0xa7, 0xeb, 0xcb,
	0xfa, 0xf4, 0x31, 0x34, 0xed, 0xba, 0x42, 0x65, 0xf6, 0x12, 0x75, 0x62, 0xbb, 0xcf, 0x99, 0xca,
	0xa2, 0x7f, 0x05, 0x4e, 0xce, 0x2d, 0xc5, 0xf7, 0x3d, 0xd8, 0xaa, 0xc9, 0x39, 0xf2, 0x31, 0x3d,
	0x77, 0x7c, 0x0b, 0x3d, 0xb7, 0x03, 0x1d, 0xcd, 0x0d, 0xb1, 0xac, 0x20, 0x8a, 0x89, 0x8f, 0x1a,
	0x34, 0x37, 0xd8, 0x5c, 0x4f, 0x8a, 0x49, 0xf8, 0x5d, 0xe8, 0xd4, 0xdf, 0x04, 0x3e, 0xf6, 0x76,
	0xed, 0x2d, 0x80, 0x29, 0x71, 0x94, 0x95, 0x49, 0x47, 0xf4, 0xdd, 0xb8, 0x69, 0xc9, 0x2a, 0x93,
	0x06, 0x03, 0xc5, 0x97, 0x4e, 0x4d, 0x16, 0x3a, 0x0e, 0xe8, 0x28, 0x76, 0x75, 0x56, 0x29, 0xc3,
	0x17, 0x70, 0x0f, 0x67, 0xa1, 0xea, 0x70, 0xe7, 0xc1, 0x17, 0xd1, 0xe6, 0x4e, 0xb0, 0xdb, 0x7e,
	0xfe, 0xa4, 0x42, 0xff, 0x43, 0x98, 0x62, 0xdc, 0x7b, 0x5f, 0x2d, 0xc0, 0x56, 0x02, 0xd0, 0x5c,
	0x00, 0xa0, 0x9e, 0xe1, 0xd6, 0x42, 0x86, 0x31, 0xfc, 0xb1, 0x92, 0xef, 0xac, 0xe3, 0x1e, 0xd8,
	0x3e, 0xd5, 0x44, 0x03, 0x6e, 0x1a, 0x7e, 0x07, 0x5a, 0x48, 0x22, 0x86, 0xaa, 0x99, 0xe9, 0xb5,
	0x2d, 0xbf, 0xcd, 0x0d, 0xf5, 0xaf, 0xd3, 0x5e, 0xc7, 0xa1, 0x5a, 0x19, 0xea, 0x35, 0xd4, 0x5d,
	0xa8, 0xa1, 0xc7, 0xd0, 0xe4, 0xe8, 0x91, 0x8e, 0x4c, 0x6f, 0xcb, 0x3a, 0xdc, 0xc4, 0xf1, 0xfe,
	0xc8, 0x44, 0xff, 0x6c, 0xd4, 0xe1, 0xae, 0x9a, 0xd2, 0x7f, 0x09, 0xee, 0xff, 0x8f, 0x7c, 0xff,
	0xc4, 0xf5, 0xf9, 0xa3, 0xe1, 0x9b, 0xd3, 0x5f, 0x90, 0xe1, 0x51, 0x92, 0xec, 0xbf, 0x3c, 0x22,
	0xc9, 0xb2, 0x86, 0x4c, 0x58, 0xc6, 0x46, 0xe6, 0x50, 0x1b, 0xd2, 0xbf, 0x59, 0x43, 0xea, 0xf9,
	0x73, 0xd8, 0xf2, 0x40, 0x7f, 0x89, 0xb1, 0x1a, 0xab, 0x19, 0xeb, 0x83, 0x1e, 0xfd, 0x81, 0x4e,
	0x09, 0x3e, 0xa2, 0x53, 0xde, 0x38, 0x96, 0xa8, 0xd3, 0x9a, 0x77, 0xfe, 0x05, 0x74, 0x16, 0x44,
	0xdb, 0x2a, 0xbd, 0x07, 0x35, 0xcd, 0x36, 0x5c, 0x54, 0x90, 0x09, 0xf3, 0xe7, 0xee, 0xc1, 0xe6,
	0xc8, 0xd9, 0xbc, 0x64, 0x2b, 0x87, 0x2b, 0x9f, 0x89, 0xd1, 0x67, 0xee, 0xc5, 0x39, 0xe7, 0x3d,
	0xbb, 0x53, 0xf9, 0x7a, 0xf7, 0x3b, 0xf9, 0x61, 0xf4, 0xc7, 0x35, 0x78, 0xb6, 0xdc, 0xd5, 0x4e,
	0xa5, 0xa1, 0x99, 0xe3, 0x51, 0xdb, 0x7c, 0xbf, 0x8d, 0x92, 0xfd, 0x02, 0x3a, 0x94, 0xdf, 0x52,
	0xc8, 0x02, 0xe5, 0xd5, 0xba, 0x2f, 0xe1, 0xde, 0x58, 0xda, 0xfa, 0x21, 0xb7, 0x7b, 0xab, 0x6f,
	0x8d, 0x25, 0x96, 0x57, 0xb5, 0xc1, 0x3e, 0x84, 0xb8, 0x41, 0x26, 0x17, 0x20, 0x59, 0xf5, 0x6c,
	0xdf, 0x1e, 0x4b, 0x35, 0x90, 0x35, 0x5c, 0x7e, 0xec, 0x90, 0x76, 0xff, 0xf0, 0xbc, 0x3e, 0x19,
	0x1c, 0x9f, 0x1c, 0x91, 0xd3, 0xd7, 0xa7, 0xfb, 0x03, 0x2b, 0x47, 0xdc, 0xb3, 0xf1, 0x92, 0x8b,
	0xb2, 0x2a, 0xc1, 0x99, 0x5e, 0x71, 0x91, 0x46, 0xbf, 0x9e, 0x2f, 0x4d, 0xfe, 0xb3, 0xa5, 0x48,
	0xb1, 0x52, 0xa0, 0x8c, 0x21, 0x06, 0x71, 0xf0, 0xf0, 0xb6, 0x9d, 0xcd, 0x42, 0x13, 0xdd, 0x77,
	0x6f, 0x38, 0xff, 0xd7, 0xd3, 0xeb, 0x83, 0x83, 0xfd, 0x93, 0x57, 0xd1, 0xaf, 0xe0, 0xc9, 0xdc,
	0xe5, 0xbe, 0xab, 0x58, 0x27, 0x28, 0xe7, 0x02, 0x9f, 0x51, 0x54, 0x41, 0x29, 0xf3, 0x55, 0xd0,
	0xb2, 0x96, 0xa1, 0x4c, 0xd9, 0x37, 0xb4, 0xfa, 0x83, 0xb5, 0xaf, 0x82, 0x7f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x52, 0x11, 0xd0, 0xff, 0x0b, 0x13, 0x00, 0x00,
}
