---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/6 10:56
---


--- 获取系统时间，毫秒级别
function GetOsTimeMillisecond()
    return luaCallGoGetOsTimeMillisecond()
end

function GetOsDateNow()
    return os.date("%Y-%m-%d %H:%M:%S",os.time())
end

function GetOsDayNow()
    return os.date("%Y-%m-%d",os.time())
end

function GetOsDateTimeNow()
    return os.date("%H：%M：%S",os.time())
end
